/**
 * Phrasings for measuring Reflex, none of them taken from its phrase bank. Set A was written
 * first, for the prototype; set B was written before any tuning, in a looser, more spoken
 * style (fillers, split words from speech recognition, indirect requests).
 */

export interface EvalCase {
  u: string;
  intent: string;
  app?: string;
  agent?: string;
  project?: string;
}

export const EVAL_APPS = [
  'Safari', 'Slack', 'Spotify', 'Figma', 'Notes', 'Notion', 'Terminal', 'Mail', 'Visual Studio Code', 'Xcode', 'Google Chrome', 'zoom.us',
  'Music', 'WhatsApp', 'Calculator', 'Calendar', 'Messages', 'System Settings', 'Finder', 'Preview', 'Photos', 'Maps', 'Reminders',
  'App Store', 'Activity Monitor', 'Claude', 'ChatGPT', 'Docker', 'Postman', 'Microsoft Word', 'Microsoft Teams', 'Keynote', 'Pages',
  'Numbers', 'TextEdit', 'QuickTime Player', 'Time Machine', 'LM Studio', 'Books', 'Podcasts', 'News', 'Clock', 'Weather',
];
export const EVAL_AGENTS = [
  { name: 'claude', label: 'Claude' },
  { name: 'codex', label: 'Codex' },
  { name: 'opencode', label: 'OpenCode' },
];
export const EVAL_PROJECTS = ['Agentic_OS', 'website', 'api', 'nova'];

const c = (intent: string, u: string, extra: Partial<EvalCase> = {}): EvalCase => ({ u, intent, ...extra });

export const SET_A: EvalCase[] = [
  c('open_app', 'could you fire up spotify', { app: 'Spotify' }),
  c('open_app', 'launch figma for me', { app: 'Figma' }),
  c('open_app', 'pull up notes', { app: 'Notes' }),
  c('open_app', 'i need the terminal', { app: 'Terminal' }),
  c('open_app', 'get safari going', { app: 'Safari' }),
  c('open_app', 'open up my mail', { app: 'Mail' }),
  c('open_app', 'show me slack', { app: 'Slack' }),
  c('open_app', 'start visual studio code please', { app: 'Visual Studio Code' }),
  c('open_app', 'bring whatsapp to the front', { app: 'WhatsApp' }),
  c('open_app', 'can you open the calculator', { app: 'Calculator' }),
  c('quit_app', 'close down slack', { app: 'Slack' }),
  c('quit_app', 'get rid of spotify', { app: 'Spotify' }),
  c('quit_app', 'exit xcode', { app: 'Xcode' }),
  c('quit_app', 'shut chrome', { app: 'Google Chrome' }),
  c('quit_app', "i'm done with figma, close it", { app: 'Figma' }),
  c('quit_app', 'terminate zoom', { app: 'zoom.us' }),
  c('quit_app', 'quit the music app', { app: 'Music' }),
  c('quit_app', 'force quit safari', { app: 'Safari' }),
  c('tell_time', "what's the time"),
  c('tell_time', 'how late is it'),
  c('tell_time', "what's today's date"),
  c('tell_time', 'do you know what time it is'),
  c('tell_time', 'which day of the week is it'),
  c('tell_time', "what's the date"),
  c('tell_time', 'time check'),
  c('tell_time', 'is it past noon yet'),
  c('set_timer', 'wake me in 20 minutes'),
  c('set_timer', 'give me a 5 minute countdown'),
  c('set_timer', 'set an alarm for ten minutes'),
  c('set_timer', 'count down from 3 minutes'),
  c('set_timer', 'timer for two minutes please'),
  c('set_timer', 'ping me in half an hour'),
  c('set_timer', 'start a 25 minute pomodoro'),
  c('set_timer', 'let me know when 15 minutes have passed'),
  c('stop_listening', 'you can stop listening now'),
  c('stop_listening', 'turn your mic off'),
  c('stop_listening', 'go to sleep nova'),
  c('stop_listening', 'stop hearing me'),
  c('stop_listening', "don't listen for a while"),
  c('stop_listening', 'pause listening'),
  c('stop_listening', 'mic off'),
  c('open_settings', 'show me your preferences'),
  c('open_settings', 'i want to change your configuration'),
  c('open_settings', 'take me to settings'),
  c('open_settings', 'open your config'),
  c('open_settings', 'let me adjust your settings'),
  c('open_settings', 'where are your options'),
  c('cancel_timer', 'kill the timer'),
  c('cancel_timer', 'never mind the countdown'),
  c('cancel_timer', 'turn off my timer'),
  c('cancel_timer', 'delete the timers'),
  c('cancel_timer', 'stop that countdown'),
  c('cancel_timer', 'remove the alarm'),
  c('agent_task', 'have claude fix the build in nova', { agent: 'claude', project: 'nova' }),
  c('agent_task', 'ask codex to write unit tests for the website', { agent: 'codex', project: 'website' }),
  c('agent_task', 'get claude to update the readme in agentic os', { agent: 'claude', project: 'Agentic_OS' }),
  c('agent_task', 'tell codex to refactor the auth module', { agent: 'codex' }),
  c('agent_task', 'can claude add dark mode to my project', { agent: 'claude' }),
  c('agent_task', 'let the agent clean up the css in the site'),
  c('agent_task', 'ask opencode to bump the dependencies', { agent: 'opencode' }),
  c('agent_task', 'codex please rename the config file in the api project', { agent: 'codex', project: 'api' }),
  c('cancel_task', 'tell claude to stop working', { agent: 'claude' }),
  c('cancel_task', 'abort the agent'),
  c('cancel_task', 'cancel what codex is doing', { agent: 'codex' }),
  c('cancel_task', 'stop the task'),
  c('cancel_task', 'halt the agent job'),
  c('cancel_task', 'make the agent quit'),
  c('stop', 'stop'),
  c('stop', 'never mind'),
  c('stop', 'forget about it'),
  c('stop', 'hush'),
  c('stop', 'quiet please'),
  c('stop', 'cancel'),
  c('stop', "that's enough"),
  c('confirm_yes', 'yes please'),
  c('confirm_yes', 'yep go for it'),
  c('confirm_yes', 'sure thing'),
  c('confirm_yes', 'do it'),
  c('confirm_yes', 'absolutely'),
  c('confirm_yes', "that's right"),
  c('confirm_yes', 'okay'),
  c('confirm_yes', 'go on then'),
  c('confirm_yes', 'affirmative'),
  c('confirm_no', 'no thanks'),
  c('confirm_no', 'nope'),
  c('confirm_no', "don't do that"),
  c('confirm_no', 'not now'),
  c('confirm_no', 'no leave it'),
  c('confirm_no', 'nah'),
  c('confirm_no', 'negative'),
  c('confirm_no', 'hold off'),
  c('chat', "what's the capital of ghana"),
  c('chat', 'explain how vaccines work'),
  c('chat', 'who wrote things fall apart'),
  c('chat', 'how do i make jollof rice'),
  c('chat', 'write me a short poem about rain'),
  c('chat', 'summarize the plot of inception'),
  c('chat', "what's the difference between tcp and udp"),
  c('chat', 'help me plan my week'),
  c('chat', 'why is the sky blue'),
  c('chat', 'tell me a joke'),
  c('other', 'and then she said she was moving to kumasi'),
  c('other', 'the match starts at eight on sky sports'),
  c('other', 'pass me the salt'),
  c('other', 'honey did you feed the dog'),
  c('other', 'breaking news tonight from the capital'),
  c('other', 'i think the meeting went well'),
  c('other', "lol that's hilarious"),
  c('other', 'yeah i saw that episode last week'),
];

export const SET_B: EvalCase[] = [
  c('open_app', 'um can you open safari real quick', { app: 'Safari' }),
  c('open_app', "i'd like to use slack", { app: 'Slack' }),
  c('open_app', 'open fig ma', { app: 'Figma' }),
  c('open_app', 'launch spot if i', { app: 'Spotify' }),
  c('open_app', 'get me into visual studio code', { app: 'Visual Studio Code' }),
  c('open_app', 'open x code please', { app: 'Xcode' }),
  c('open_app', 'switch over to chrome', { app: 'Google Chrome' }),
  c('open_app', 'show me my calendar', { app: 'Calendar' }),
  c('open_app', 'start zoom', { app: 'zoom.us' }),
  c('open_app', 'put spotify on', { app: 'Spotify' }),
  c('quit_app', 'please quit slack now', { app: 'Slack' }),
  c('quit_app', 'close the zoom app', { app: 'zoom.us' }),
  c('quit_app', 'i want spotify closed', { app: 'Spotify' }),
  c('quit_app', 'shut down x code', { app: 'Xcode' }),
  c('quit_app', "kill chrome it's frozen", { app: 'Google Chrome' }),
  c('quit_app', 'exit out of figma', { app: 'Figma' }),
  c('quit_app', 'close my calendar', { app: 'Calendar' }),
  c('quit_app', 'quit safari for me', { app: 'Safari' }),
  c('tell_time', 'hey what time have we got'),
  c('tell_time', "could you tell me today's date"),
  c('tell_time', "what's the time right now"),
  c('tell_time', "what's the date today please"),
  c('tell_time', 'what day of the month is it'),
  c('tell_time', 'is it already evening'),
  c('tell_time', 'the time please'),
  c('set_timer', 'set a timer for seven minutes'),
  c('set_timer', 'remind me in an hour'),
  c('set_timer', 'start a countdown of ninety seconds'),
  c('set_timer', 'can you set a timer for the tea, four minutes'),
  c('set_timer', 'i need an alarm in 30 minutes'),
  c('set_timer', 'time eleven minutes for me'),
  c('set_timer', 'timer, three minutes'),
  c('stop_listening', 'okay stop listening please'),
  c('stop_listening', 'go to sleep for now'),
  c('stop_listening', 'turn off your microphone'),
  c('stop_listening', 'mute your mic'),
  c('stop_listening', 'stop listening to everything i say'),
  c('stop_listening', 'you can sleep now'),
  c('open_settings', 'open up the settings'),
  c('open_settings', 'can i see your settings'),
  c('open_settings', "i'd like to change your wake word"),
  c('open_settings', 'open the preferences window'),
  c('open_settings', 'settings'),
  c('cancel_timer', 'cancel that timer'),
  c('cancel_timer', 'stop my countdown'),
  c('cancel_timer', "i don't need the timer, cancel it"),
  c('cancel_timer', 'clear all my timers please'),
  c('cancel_timer', 'switch the timer off'),
  c('agent_task', 'ask claude to add tests to the website', { agent: 'claude', project: 'website' }),
  c('agent_task', 'get codex to fix the typo in the readme of the api', { agent: 'codex', project: 'api' }),
  c('agent_task', 'have claude update the dependencies in agentic os', { agent: 'claude', project: 'Agentic_OS' }),
  c('agent_task', 'tell codex to write a changelog for nova', { agent: 'codex', project: 'nova' }),
  c('agent_task', 'claude, add a loading spinner to the site', { agent: 'claude' }),
  c('agent_task', 'can you get the agent to fix the broken links in the website', { project: 'website' }),
  c('agent_task', 'let codex migrate the database in the api project', { agent: 'codex', project: 'api' }),
  c('cancel_task', 'stop claude', { agent: 'claude' }),
  c('cancel_task', "tell codex to stop what it's doing", { agent: 'codex' }),
  c('cancel_task', "cancel the agent's work"),
  c('cancel_task', "abort claude's task", { agent: 'claude' }),
  c('cancel_task', 'stop the agent now'),
  c('stop', 'stop it please'),
  c('stop', 'never mind that'),
  c('stop', 'okay forget it'),
  c('stop', 'be quiet'),
  c('stop', 'shush'),
  c('confirm_yes', 'yes do it'),
  c('confirm_yes', 'yeah go ahead'),
  c('confirm_yes', 'sure go on'),
  c('confirm_yes', 'yes, confirm'),
  c('confirm_yes', 'okay, sounds good'),
  c('confirm_yes', 'yep'),
  c('confirm_no', "no, don't"),
  c('confirm_no', 'no, leave it'),
  c('confirm_no', "nah don't bother"),
  c('confirm_no', 'no thank you'),
  c('confirm_no', "don't do that please"),
  c('chat', "what's the tallest building in the world"),
  c('chat', 'can you explain what an api is'),
  c('chat', 'how do i change a car tyre'),
  c('chat', 'write a limerick about a cat'),
  c('chat', 'who painted the mona lisa'),
  c('chat', "what's 15 percent of 80"),
  c('chat', 'give me some tips for a job interview'),
  c('chat', 'what does photosynthesis produce'),
  c('chat', "tell me about ghana's independence"),
  c('chat', 'how many continents are there'),
  c('other', 'no i told him to bring the chairs'),
  c('other', 'the weather today will be sunny with some clouds'),
  c('other', 'are you coming to church on sunday'),
  c('other', "i can't believe he said that"),
  c('other', 'this song is my favourite'),
  c('other', 'the bus is late again'),
  c('other', 'what are you cooking tonight dear'),
  c('other', "and that's the end of the first half"),
];

/** Written after the first round of tuning and kept aside: measured once, at the end. */
export const SET_C: EvalCase[] = [
  c('open_app', 'open the notes app', { app: 'Notes' }),
  c('open_app', 'yo launch slack', { app: 'Slack' }),
  c('open_app', 'could you please start safari for me', { app: 'Safari' }),
  c('open_app', 'open chat gpt', { app: 'ChatGPT' }),
  c('open_app', 'fire up docker', { app: 'Docker' }),
  c('open_app', 'i wanna use postman', { app: 'Postman' }),
  c('open_app', 'bring up activity monitor', { app: 'Activity Monitor' }),
  c('open_app', 'go to spotify', { app: 'Spotify' }),
  c('quit_app', 'close postman', { app: 'Postman' }),
  c('quit_app', 'quit docker please', { app: 'Docker' }),
  c('quit_app', 'shut spotify down', { app: 'Spotify' }),
  c('quit_app', 'can you close the calculator', { app: 'Calculator' }),
  c('quit_app', "i'm finished with safari you can close it", { app: 'Safari' }),
  c('quit_app', 'exit notion', { app: 'Notion' }),
  c('quit_app', 'quit chat gpt', { app: 'ChatGPT' }),
  c('tell_time', "what's the time please"),
  c('tell_time', 'tell me what day it is'),
  c('tell_time', "what's the date today"),
  c('tell_time', 'do you know the date'),
  c('tell_time', 'got the time'),
  c('tell_time', "what's today"),
  c('set_timer', 'set a timer for 6 minutes'),
  c('set_timer', 'remind me in 5'),
  c('set_timer', 'start a two minute timer please'),
  c('set_timer', 'can you count down 45 seconds'),
  c('set_timer', 'set a timer for an hour'),
  c('set_timer', 'put on a 10 minute timer'),
  c('set_timer', 'i need a 3 minute countdown'),
  c('stop_listening', 'stop listening now'),
  c('stop_listening', 'turn off the mic'),
  c('stop_listening', 'go to sleep please'),
  c('stop_listening', 'mute'),
  c('stop_listening', 'you can stop listening'),
  c('open_settings', 'open settings please'),
  c('open_settings', 'show your preferences'),
  c('open_settings', 'i want to change the voice'),
  c('open_settings', 'open the config'),
  c('open_settings', 'go into settings'),
  c('cancel_timer', 'cancel the countdown please'),
  c('cancel_timer', 'stop the timers'),
  c('cancel_timer', 'turn the timer off'),
  c('cancel_timer', 'cancel my alarm'),
  c('cancel_timer', "i don't want the timer anymore"),
  c('agent_task', 'ask codex to add a login page to the website', { agent: 'codex', project: 'website' }),
  c('agent_task', 'have claude write tests for the api', { agent: 'claude', project: 'api' }),
  c('agent_task', 'tell claude to fix the lint errors in agentic os', { agent: 'claude', project: 'Agentic_OS' }),
  c('agent_task', 'get opencode to update the readme', { agent: 'opencode' }),
  c('agent_task', 'codex, refactor the database layer in nova', { agent: 'codex', project: 'nova' }),
  c('agent_task', 'can the agent add comments to the code'),
  c('cancel_task', 'stop codex', { agent: 'codex' }),
  c('cancel_task', 'cancel the task'),
  c('cancel_task', 'tell the agent to stop now'),
  c('cancel_task', 'make claude stop', { agent: 'claude' }),
  c('cancel_task', 'abort what the agent is doing'),
  c('stop', 'stop please'),
  c('stop', 'never mind, forget it'),
  c('stop', 'shut up'),
  c('stop', "that's enough, thanks"),
  c('stop', 'okay never mind'),
  c('confirm_yes', 'yes'),
  c('confirm_yes', 'sure, go ahead'),
  c('confirm_yes', "yeah that's fine"),
  c('confirm_yes', 'go ahead please'),
  c('confirm_yes', 'definitely, go'),
  c('confirm_yes', 'uh yes please'),
  c('confirm_no', 'no'),
  c('confirm_no', 'no, cancel it'),
  c('confirm_no', "don't do it"),
  c('confirm_no', 'nope, leave it'),
  c('confirm_no', 'no no no'),
  c('confirm_no', 'not right now'),
  c('chat', 'how does wifi work'),
  c('chat', "what's the capital of kenya"),
  c('chat', 'tell me a fun fact about space'),
  c('chat', 'write a short story about a robot'),
  c('chat', 'how many days are in a leap year'),
  c('chat', 'who discovered penicillin'),
  c('chat', 'what should i name my dog'),
  c('chat', 'explain blockchain in simple terms'),
  c('other', 'did you remember to lock the door'),
  c('other', 'the final score was two nil'),
  c('other', "i'm going to the market later"),
  c('other', 'good evening and welcome to the program'),
  c('other', "she's been working there for years"),
  c('other', 'turn around and look at this'),
  c('other', 'we need to buy more rice'),
  c('other', 'that was a great goal'),
];

/** Replies while Nova waits for a yes or no (e.g. "Quit Spotify?"). Stop counts as a no. */
export const REPLIES: { u: string; yes: boolean }[] = [
  { u: 'sure', yes: true },
  { u: 'go on then', yes: true },
  { u: 'yeah', yes: true },
  { u: 'please do', yes: true },
  { u: 'okay', yes: true },
  { u: 'fine', yes: true },
  { u: 'yes quit it', yes: true },
  { u: 'nah', yes: false },
  { u: 'no', yes: false },
  { u: 'leave it', yes: false },
  { u: 'not now', yes: false },
  { u: "don't", yes: false },
  { u: 'never mind', yes: false },
  { u: 'wait no keep it open', yes: false },
];

/**
 * Written before Reflex's larger training set. Heavier on what trips a System 1 up -
 * background speech that mentions apps, times and "stop", questions that sound like
 * commands, non-native and Ghanaian phrasing. Its misses were seen once, before training,
 * so it's a development set: the clean held-out sets are C and E.
 */
export const SET_D: EvalCase[] = [
  c('open_app', 'hey can you pull up whatsapp for me', { app: 'WhatsApp' }),
  c('open_app', 'open notion', { app: 'Notion' }),
  c('open_app', 'i wanna check my email, open mail', { app: 'Mail' }),
  c('open_app', 'bring up the calculator real quick', { app: 'Calculator' }),
  c('open_app', 'okay open terminal', { app: 'Terminal' }),
  c('open_app', 'launch teams', { app: 'Microsoft Teams' }),
  c('open_app', 'could you get postman open', { app: 'Postman' }),
  c('open_app', 'open up docker for me please', { app: 'Docker' }),
  c('open_app', 'start the music app', { app: 'Music' }),
  c('open_app', 'go to my messages', { app: 'Messages' }),
  c('open_app', 'i need to see my reminders', { app: 'Reminders' }),
  c('open_app', 'open vs code', { app: 'Visual Studio Code' }),
  c('open_app', 'can i get chrome up please', { app: 'Google Chrome' }),
  c('open_app', 'fire up lm studio', { app: 'LM Studio' }),
  c('open_app', 'open the photos app', { app: 'Photos' }),
  c('open_app', 'show me the finder', { app: 'Finder' }),
  c('open_app', 'flip over to safari', { app: 'Safari' }),
  c('open_app', 'jump into slack', { app: 'Slack' }),
  c('open_app', 'open keynote i have to finish my slides', { app: 'Keynote' }),
  c('open_app', 'um open uh spotify', { app: 'Spotify' }),
  c('open_app', 'please launch microsoft word', { app: 'Microsoft Word' }),
  c('open_app', 'get figma running', { app: 'Figma' }),
  c('open_app', 'open the app store', { app: 'App Store' }),
  c('open_app', 'open activity monitor', { app: 'Activity Monitor' }),
  c('open_app', 'open maps', { app: 'Maps' }),
  c('open_app', "i'd like to open numbers", { app: 'Numbers' }),
  c('open_app', 'can you start quicktime', { app: 'QuickTime Player' }),
  c('open_app', 'open text edit', { app: 'TextEdit' }),
  c('open_app', 'open chat gpt', { app: 'ChatGPT' }),
  c('open_app', 'open the claude app', { app: 'Claude' }),
  c('open_app', 'nova open podcasts', { app: 'Podcasts' }),
  c('open_app', 'let me see the weather app', { app: 'Weather' }),
  c('open_app', 'open system settings', { app: 'System Settings' }),
  c('open_app', 'open my calendar please', { app: 'Calendar' }),
  c('open_app', 'load up books', { app: 'Books' }),
  c('open_app', 'open preview', { app: 'Preview' }),

  c('quit_app', 'close whatsapp', { app: 'WhatsApp' }),
  c('quit_app', 'quit teams please', { app: 'Microsoft Teams' }),
  c('quit_app', 'shut down docker', { app: 'Docker' }),
  c('quit_app', "close out slack i'm done for the day", { app: 'Slack' }),
  c('quit_app', 'kill postman', { app: 'Postman' }),
  c('quit_app', 'quit notion', { app: 'Notion' }),
  c('quit_app', 'can you close the calculator', { app: 'Calculator' }),
  c('quit_app', 'exit terminal', { app: 'Terminal' }),
  c('quit_app', 'get rid of the photos app', { app: 'Photos' }),
  c('quit_app', "please close spotify it's too loud", { app: 'Spotify' }),
  c('quit_app', 'close keynote', { app: 'Keynote' }),
  c('quit_app', 'quit lm studio', { app: 'LM Studio' }),
  c('quit_app', 'shut vs code', { app: 'Visual Studio Code' }),
  c('quit_app', 'close all of chrome', { app: 'Google Chrome' }),
  c('quit_app', 'exit out of messages', { app: 'Messages' }),
  c('quit_app', 'quit the music player', { app: 'Music' }),
  c('quit_app', 'force close xcode', { app: 'Xcode' }),
  c('quit_app', 'close word', { app: 'Microsoft Word' }),
  c('quit_app', 'shut the mail app', { app: 'Mail' }),
  c('quit_app', 'stop zoom', { app: 'zoom.us' }),
  c('quit_app', 'switch off safari', { app: 'Safari' }),
  c('quit_app', "i don't need figma anymore close it", { app: 'Figma' }),
  c('quit_app', 'close activity monitor', { app: 'Activity Monitor' }),
  c('quit_app', 'quit preview', { app: 'Preview' }),
  c('quit_app', 'can you exit chat gpt', { app: 'ChatGPT' }),

  c('tell_time', 'what time is it right now please'),
  c('tell_time', 'do you know the time'),
  c('tell_time', "how's the time"),
  c('tell_time', "what's the time looking like"),
  c('tell_time', 'tell me what time it is'),
  c('tell_time', 'what day is today'),
  c('tell_time', 'today is what date'),
  c('tell_time', 'is it friday today'),
  c('tell_time', "what's the day and time"),
  c('tell_time', 'how much time is it'),
  c('tell_time', 'what time we got'),
  c('tell_time', 'remind me what day it is'),
  c('tell_time', 'is it past midnight'),
  c('tell_time', 'what month are we in'),
  c('tell_time', 'which date is it today'),
  c('tell_time', 'time'),
  c('tell_time', 'the date please'),
  c('tell_time', 'is it the weekend yet'),
  c('tell_time', 'are we in september'),
  c('tell_time', "what's the current date and time"),

  c('set_timer', 'set a timer for twenty minutes please'),
  c('set_timer', 'timer five minutes'),
  c('set_timer', 'can you give me a two minute warning'),
  c('set_timer', 'remind me in ten minutes to check the oven'),
  c('set_timer', 'start a timer for 45 seconds'),
  c('set_timer', 'count down one hour'),
  c('set_timer', 'set a 15 minute timer for my break'),
  c('set_timer', 'alert me after 30 minutes'),
  c('set_timer', 'let me know when an hour has passed'),
  c('set_timer', 'time my presentation for 5 minutes'),
  c('set_timer', "wake me in twenty minutes i'm taking a nap"),
  c('set_timer', 'put on a timer for three minutes for the eggs'),
  c('set_timer', 'timer for an hour'),
  c('set_timer', 'start a quarter of an hour countdown'),
  c('set_timer', 'can you set an alarm for 10 minutes from now'),
  c('set_timer', 'ring in 5 minutes'),
  c('set_timer', 'give me a shout in forty minutes'),
  c('set_timer', 'do a countdown of 2 minutes'),
  c('set_timer', 'nova timer 8 minutes'),
  c('set_timer', 'set timer 30 seconds'),
  c('set_timer', 'remind me in two hours'),
  c('set_timer', 'start a pomodoro'),
  c('set_timer', 'i need a 90 second timer'),
  c('set_timer', 'let me know in half an hour'),
  c('set_timer', 'can you time me, one minute'),

  c('stop_listening', 'stop listening for now'),
  c('stop_listening', 'you can turn your mic off'),
  c('stop_listening', 'go to sleep please'),
  c('stop_listening', 'stop listening nova'),
  c('stop_listening', 'mute'),
  c('stop_listening', 'turn off your ears'),
  c('stop_listening', "i don't need you right now stop listening"),
  c('stop_listening', 'switch off the microphone'),
  c('stop_listening', 'you can rest now'),
  c('stop_listening', 'stop listening to the room'),
  c('stop_listening', 'microphone off'),
  c('stop_listening', 'sleep mode'),

  c('open_settings', 'open your settings page'),
  c('open_settings', 'show me the settings screen'),
  c('open_settings', 'take me to your preferences'),
  c('open_settings', 'open nova settings'),
  c('open_settings', 'i want to change how you sound'),
  c('open_settings', 'pull up the settings'),
  c('open_settings', 'let me see your configuration'),
  c('open_settings', 'open preferences please'),
  c('open_settings', 'settings menu'),
  c('open_settings', 'can you open the settings panel'),
  c('open_settings', 'i need to change your wake word'),
  c('open_settings', 'go into settings'),

  c('cancel_timer', 'please stop my timer'),
  c('cancel_timer', 'cancel the countdown for the eggs'),
  c('cancel_timer', 'turn the timer off'),
  c('cancel_timer', 'cancel the ten minute timer'),
  c('cancel_timer', "i don't need that timer"),
  c('cancel_timer', 'get rid of all the timers'),
  c('cancel_timer', 'delete my countdown'),
  c('cancel_timer', 'kill the alarm'),
  c('cancel_timer', 'timer off'),
  c('cancel_timer', 'clear the timer'),
  c('cancel_timer', 'cancel my reminder'),
  c('cancel_timer', 'abort the countdown'),

  c('agent_task', 'claude fix the login bug in the website', { agent: 'claude', project: 'website' }),
  c('agent_task', 'get codex to add pagination to the api', { agent: 'codex', project: 'api' }),
  c('agent_task', 'ask claude to write tests for nova', { agent: 'claude', project: 'nova' }),
  c('agent_task', 'have opencode clean up the imports in agentic os', { agent: 'opencode', project: 'Agentic_OS' }),
  c('agent_task', 'tell claude to make the header sticky on the website', { agent: 'claude', project: 'website' }),
  c('agent_task', 'codex can you update the readme in the api', { agent: 'codex', project: 'api' }),
  c('agent_task', 'i want claude to refactor the settings code in nova', { agent: 'claude', project: 'nova' }),
  c('agent_task', 'let codex add error handling to the api', { agent: 'codex', project: 'api' }),
  c('agent_task', 'ask the agent to fix the typescript errors'),
  c('agent_task', 'get claude to set up linting for the website', { agent: 'claude', project: 'website' }),
  c('agent_task', 'have codex write a migration script', { agent: 'codex' }),
  c('agent_task', 'send claude to fix the flaky test in nova', { agent: 'claude', project: 'nova' }),
  c('agent_task', 'can opencode add a dark theme to the website', { agent: 'opencode', project: 'website' }),
  c('agent_task', 'claude, bump the version number in agentic os', { agent: 'claude', project: 'Agentic_OS' }),
  c('agent_task', 'tell codex to generate api docs', { agent: 'codex' }),
  c('agent_task', 'ask claude to translate the ui strings in nova', { agent: 'claude', project: 'nova' }),
  c('agent_task', 'put codex on the performance issue in the api', { agent: 'codex', project: 'api' }),
  c('agent_task', 'get the agent to add a contact form to the website', { project: 'website' }),
  c('agent_task', 'have claude write a script to back up my photos', { agent: 'claude' }),
  c('agent_task', 'claude please review my last commit in agentic os', { agent: 'claude', project: 'Agentic_OS' }),
  c('agent_task', 'ask codex to delete the dead code in nova', { agent: 'codex', project: 'nova' }),
  c('agent_task', 'tell opencode to fix the docker setup in the api', { agent: 'opencode', project: 'api' }),
  c('agent_task', 'can claude add unit tests for the parser', { agent: 'claude' }),
  c('agent_task', 'let claude optimize the images on the website', { agent: 'claude', project: 'website' }),
  c('agent_task', 'i need codex to rewrite the auth flow in nova', { agent: 'codex', project: 'nova' }),

  c('cancel_task', 'stop it claude', { agent: 'claude' }),
  c('cancel_task', 'cancel the claude task', { agent: 'claude' }),
  c('cancel_task', 'ask codex to stop', { agent: 'codex' }),
  c('cancel_task', 'abort what the agent is doing'),
  c('cancel_task', 'kill the codex job', { agent: 'codex' }),
  c('cancel_task', 'stop all the agents'),
  c('cancel_task', 'cancel the task claude is running', { agent: 'claude' }),
  c('cancel_task', 'the agent can stop now'),
  c('cancel_task', 'halt the coding job'),
  c('cancel_task', 'make codex stop working on it', { agent: 'codex' }),
  c('cancel_task', 'end the agent task'),
  c('cancel_task', 'call off claude', { agent: 'claude' }),

  c('stop', "okay that's enough"),
  c('stop', 'please stop talking now'),
  c('stop', 'quiet nova'),
  c('stop', 'shush now'),
  c('stop', 'nope forget it'),
  c('stop', 'cut it out'),
  c('stop', "that's fine you can stop"),
  c('stop', 'hold it'),
  c('stop', 'enough enough'),
  c('stop', 'shut it'),
  c('stop', 'no need, forget about it'),
  c('stop', 'stop please'),
  c('stop', 'okay okay stop'),
  c('stop', 'never mind i got it'),

  c('confirm_yes', 'yes go on'),
  c('confirm_yes', 'yeah sure'),
  c('confirm_yes', 'okay go ahead then'),
  c('confirm_yes', 'please go ahead'),
  c('confirm_yes', 'do that'),
  c('confirm_yes', "yeah that's fine"),
  c('confirm_yes', 'yup do it'),
  c('confirm_yes', 'correct, go ahead'),
  c('confirm_yes', 'sure why not'),
  c('confirm_yes', 'alright do it'),
  c('confirm_yes', 'yes yes'),
  c('confirm_yes', "that's okay, proceed"),
  c('confirm_yes', 'of course go ahead'),
  c('confirm_yes', 'you can do it'),

  c('confirm_no', 'no no no'),
  c('confirm_no', 'please don\'t'),
  c('confirm_no', 'no, not that'),
  c('confirm_no', 'i said no'),
  c('confirm_no', "nope don't"),
  c('confirm_no', 'no leave it as it is'),
  c('confirm_no', 'not really'),
  c('confirm_no', 'no, i changed my mind'),
  c('confirm_no', "don't do anything"),
  c('confirm_no', "no thanks i'm good"),
  c('confirm_no', 'nah leave it'),
  c('confirm_no', "cancel, don't do it"),
  c('confirm_no', 'absolutely not'),
  c('confirm_no', 'no keep it'),
  c('confirm_no', "wait, don't"),

  c('chat', 'who are you'),
  c('chat', 'what can you do'),
  c('chat', 'how do i take a screenshot on a mac'),
  c('chat', "what's the best laptop for programming"),
  c('chat', 'explain the difference between let and const'),
  c('chat', 'what is the weather like in accra today'),
  c('chat', 'how long should i boil eggs'),
  c('chat', 'what time does the sun set today'),
  c('chat', 'how many minutes are in a day'),
  c('window_control', 'what apps do i have open'), // Hands answers it itself (the windows skill lists them); it was chat before
  c('chat', 'why does my mac keep freezing'),
  c('chat', 'can you help me write a message to my landlord'),
  c('chat', "what's a good song to focus to"),
  c('chat', 'how do i use a timer in python'),
  c('chat', 'who won the premier league last season'),
  c('chat', 'tell me about kwame nkrumah'),
  c('chat', "what's the meaning of serendipity"),
  c('chat', "how do i close a program that's not responding on mac"),
  c('chat', 'is spotify better than apple music'),
  c('chat', 'recommend a podcast about history'),
  c('chat', 'write a tweet about our product launch'),
  c('chat', 'what should i name my startup'),
  c('chat', 'how does a vpn work'),
  c('chat', 'summarize the news for me'),
  c('chat', 'give me a motivational quote'),
  c('chat', "what's the difference between ram and storage"),
  c('chat', 'how do i stop procrastinating'),
  c('chat', 'can you explain docker to me'),
  c('chat', 'what is notion used for'),
  c('chat', 'how do you say thank you in twi'),
  c('chat', "what's two plus two"),
  c('chat', 'how many hours of sleep do i need'),
  c('chat', 'where is the nearest hospital'),
  c('chat', 'what year did ghana gain independence'),
  c('chat', 'tell me something about space'),
  c('chat', 'why do we dream'),
  c('chat', "what's the fastest animal"),
  c('chat', 'how can i learn to code'),
  c('chat', 'compare slack and teams for a small team'),
  c('chat', 'what does a product manager do'),
  c('chat', 'help me come up with a birthday message for my mum'),
  c('chat', 'is it going to rain tomorrow'),
  c('chat', 'how old is the earth'),
  c('chat', "what's the best way to save money"),
  c('chat', 'explain quantum computing simply'),

  c('other', 'and now over to our correspondent in kumasi'),
  c('other', 'the minister is expected to address parliament tomorrow'),
  c('other', 'shares of tech companies rose sharply this afternoon'),
  c('other', 'the prime minister said the talks were productive'),
  c('other', 'stay with us, more after these messages'),
  c('other', 'tonight on the show we have a very special guest'),
  c('other', 'temperatures will drop overnight across the north'),
  c('other', 'the kick off is at seven thirty'),
  c('other', 'he shoots, he scores'),
  c('other', 'the home team leads by two goals'),
  c('other', "that's the final whistle"),
  c('other', 'click the link in the description'),
  c('other', "don't forget to like and subscribe"),
  c('other', "in today's video i'll show you how to cook rice"),
  c('other', 'thanks for listening to the podcast'),
  c('other', 'our next caller is on the line'),
  c('other', 'hello, can you hear me? the network is bad'),
  c('other', "i'll send you the document by five"),
  c('other', 'mummy where are my school shoes'),
  c('other', 'close the door behind you please'),
  c('other', "open the window it's hot in here"),
  c('other', 'turn off the lights when you leave'),
  c('other', 'set the table, dinner is ready'),
  c('other', 'did you remember to lock the car'),
  c('other', 'can you pick up the kids at three'),
  c('other', "let's start the meeting"),
  c('other', 'can everyone see my screen'),
  c('other', "you're on mute"),
  c('other', 'sorry you broke up there, say that again'),
  c('other', "i'll be back in five minutes"),
  c('other', 'give me a minute'),
  c('other', 'who took my charger'),
  c('other', 'the food is getting cold'),
  c('other', "we're running late for the flight"),
  c('other', 'i sent the invoice yesterday'),
  c('other', 'slack is down again for everyone'),
  c('other', 'my spotify subscription expired'),
  c('other', 'i left chrome open all night'),
  c('other', 'the timer on the microwave is beeping'),
  c('other', 'what time did you get home last night'),
  c('other', 'is it your turn to cook today'),
  c('other', "yes, i'm coming"),
  c('other', "no, i'm not hungry"),
  c('other', 'stop running in the house'),
  c('other', 'quit playing games and do your homework'),
  c('other', 'the settings on this camera are confusing'),
  c('other', "i'm going to sleep, good night"),
  c('other', 'the kids watched cartoons all afternoon'),
  c('other', 'the pastor preached about patience'),
  c('other', 'this jollof is really nice'),
  c('other', 'the market was so crowded today'),
  c('other', 'hurry up, the taxi is waiting'),
  c('other', "i can't find the remote anywhere"),
  c('other', "she's on her way now"),
  c('other', 'he forgot his wallet at the office'),
  c('other', "ask your father when he's coming"),
  c('other', 'tell your brother to come and eat'),

  // Nova's hands (written before any of their intents were measured).
  c('system_control', 'bring the sound down to twenty percent'),
  c('system_control', 'crank it up a bit i can barely hear anything'),
  c('system_control', 'the screen is way too bright tone it down'),
  c('system_control', 'switch the laptop over to dark appearance'),
  c('system_control', 'is my bluetooth switched on right now'),
  c('system_control', 'go into do not disturb for the next hour'),
  c('system_control', "lock up the mac i'm stepping out"),
  c('system_control', 'how long have i got left on this battery'),
  c('media_control', 'skip ahead to the next one'),
  c('media_control', 'pause whatever is playing'),
  c('media_control', 'who sings this one'),
  c('media_control', 'throw on some afro house'),
  c('media_control', 'go back to the song before'),
  c('window_control', 'snap chrome to the right side of the screen', { app: 'Google Chrome' }),
  c('window_control', 'make this window take up the whole screen'),
  c('window_control', 'push slack over to my second monitor', { app: 'Slack' }),
  c('window_control', 'shrink finder down to the dock', { app: 'Finder' }),
  c('window_control', 'lay out my windows the way i saved for writing'),
  c('files', 'where did i put my passport scan'),
  c('files', 'pull up the spreadsheet i was editing yesterday'),
  c('files', 'chuck the old draft in the bin'),
  c('files', 'give me a summary of the lease agreement pdf'),
  c('files', 'shift the tax return file into my documents'),
  c('clipboard', 'what have i got copied right now'),
  c('clipboard', 'stick your last answer on my clipboard'),
  c('clipboard', 'grab the address of this page for me'),
  c('run_shortcut', 'fire off my water tracker shortcut'),
  c('run_shortcut', 'kick off the shortcut called focus hour'),
  c('ui_control', 'hit the submit button'),
  c('ui_control', 'type in see you tomorrow'),
  c('ui_control', 'scroll back up to the top'),
  c('ui_control', 'press command and w'),
  c('computer_task', 'go on amazon and reorder my usual coffee for me'),
  c('computer_task', 'fill out the rsvp form on this page for me'),
  c('other', 'my mum keeps turning the volume up on the telly'),
  c('other', 'just click the link i sent you in the group chat'),
  c('other', 'i dragged all my photos into the new folder last night'),
  c('chat', 'why does bluetooth drain my battery so fast'),
  // Nova's text size (development cases; the phrasings Reflex learns from are in phrases.ts and grammar.ts).
  c('text_size', 'these captions are really hard to read, blow them up'),
  c('text_size', 'can the writing on your screen be a touch larger'),
  c('text_size', 'shrink your text back down a little'),
  c('text_size', 'go to one hundred and twenty percent on the text'),
  c('text_size', 'put the font size back where it started'),
  c('text_size', 'how large is the font set at the moment'),
  c('text_size', 'i need the letters to be much bigger'),
  c('text_size', 'your words are huge, bring them down'),
];

/**
 * Written by a separate agent that never saw Reflex's training data or the other sets, so
 * nobody who tuned Reflex wrote it. Held out: never tune to it.
 */
export const SET_E: EvalCase[] = [
  c('open_app', 'put spot if i on i need some background noise to focus', { app: 'Spotify' }),
  c('open_app', 'um can you pull up fig ma for me', { app: 'Figma' }),
  c('open_app', 'uh get x code open', { app: 'Xcode' }),
  c('open_app', 'switch over to note shun', { app: 'Notion' }),
  c('open_app', 'can you launch v s code please', { app: 'Visual Studio Code' }),
  c('open_app', 'kindly open chrome for me', { app: 'Google Chrome' }),
  c('open_app', 'i need a terminal window', { app: 'Terminal' }),
  c('open_app', 'jump to slack i wanna see if anyone replied', { app: 'Slack' }),
  c('open_app', 'get zoom open my meeting starts in 2 minutes', { app: 'zoom.us' }),
  c('open_app', 'abeg open whats app for me', { app: 'WhatsApp' }),
  c('open_app', 'get safari up i need to look something up', { app: 'Safari' }),
  c('open_app', 'pop open the calendar app', { app: 'Calendar' }),
  c('open_app', 'i need to text my sister so open messages', { app: 'Messages' }),
  c('open_app', 'take me to system settings on the mac the bluetooth is acting up', { app: 'System Settings' }),
  c('open_app', 'can i get maps up i need directions to the airport', { app: 'Maps' }),
  c('open_app', 'bring up reminders i need to add something to my list', { app: 'Reminders' }),
  c('open_app', 'activity monitor please something is eating my cpu', { app: 'Activity Monitor' }),
  c('open_app', 'launch the claude desktop app', { app: 'Claude' }),
  c('open_app', 'could you open up chat g p t', { app: 'ChatGPT' }),
  c('open_app', 'start docker i need my containers running', { app: 'Docker' }),
  c('open_app', 'fire up post man so i can test this endpoint', { app: 'Postman' }),
  c('open_app', 'get teams going the standup is about to start', { app: 'Microsoft Teams' }),
  c('open_app', 'i want to write a letter in pages can you open it', { app: 'Pages' }),
  c('open_app', 'launch quicktime i want to record my screen', { app: 'QuickTime Player' }),
  c('open_app', 'open l m studio i want to load a model', { app: 'LM Studio' }),
  c('open_app', 'switch to the weather app', { app: 'Weather' }),
  c('open_app', 'let me jot something down open notes', { app: 'Notes' }),
  c('open_app', 'open the clock app i wanna check my alarms', { app: 'Clock' }),
  c('quit_app', 'force quit chrome it froze again', { app: 'Google Chrome' }),
  c('quit_app', 'quit spot if i i\'m done with it for today', { app: 'Spotify' }),
  c('quit_app', 'i\'m done with zoom you can close it now', { app: 'zoom.us' }),
  c('quit_app', 'close out of word without saving', { app: 'Microsoft Word' }),
  c('quit_app', 'exit docker desktop', { app: 'Docker' }),
  c('quit_app', 'kill x code it\'s hogging all my ram', { app: 'Xcode' }),
  c('quit_app', 'please quit teams before it pings me again', { app: 'Microsoft Teams' }),
  c('quit_app', 'close whatsapp i need to focus', { app: 'WhatsApp' }),
  c('quit_app', 'shut down l m studio the fans are going crazy', { app: 'LM Studio' }),
  c('quit_app', 'quit out of post man', { app: 'Postman' }),
  c('quit_app', 'close fig ma i\'m finished for the day', { app: 'Figma' }),
  c('quit_app', 'get notion off my screen close it', { app: 'Notion' }),
  c('quit_app', 'you can close the calculator now', { app: 'Calculator' }),
  c('quit_app', 'um quit the music app', { app: 'Music' }),
  c('quit_app', 'close preview all those pdfs are cluttering everything', { app: 'Preview' }),
  c('quit_app', 'close keynote the presentation is over', { app: 'Keynote' }),
  c('quit_app', 'quit mail for now it\'s way too distracting', { app: 'Mail' }),
  c('quit_app', 'text edit can go close it', { app: 'TextEdit' }),
  c('quit_app', 'close vs code i\'m calling it a night', { app: 'Visual Studio Code' }),
  c('quit_app', 'close safari completely not just the window', { app: 'Safari' }),
  c('quit_app', 'abeg close slack make i concentrate small', { app: 'Slack' }),
  c('quit_app', 'exit the claude app', { app: 'Claude' }),
  c('tell_time', 'have you got the time'),
  c('tell_time', 'is today tuesday or wednesday i\'ve completely lost track'),
  c('tell_time', 'uh what\'s today\'s date again'),
  c('tell_time', 'is it still september'),
  c('tell_time', 'remind me what year it is'),
  c('tell_time', 'how late is it'),
  c('tell_time', 'abeg wetin be the time now'),
  c('tell_time', 'nova time check please'),
  c('tell_time', 'is it past noon yet'),
  c('tell_time', 'which day is today'),
  c('tell_time', 'is it the twenty seventh today'),
  c('tell_time', 'hey what month are we in'),
  c('tell_time', 'give me the time real quick'),
  c('tell_time', 'is it morning or evening right now i just woke up from a nap and i\'m so confused'),
  c('tell_time', 'can you check the time for me'),
  c('tell_time', 'please what is the date of today'),
  c('tell_time', 'is today a weekday'),
  c('tell_time', 'has it gone six yet'),
  c('tell_time', 'what\'s the day and date'),
  c('tell_time', 'how much is the time now'),
  c('set_timer', 'put a timer on for 8 minutes'),
  c('set_timer', 'can you count down twenty five minutes for me'),
  c('set_timer', 'so um remind me in half an hour to call my mum'),
  c('set_timer', 'give me an alert after forty five minutes'),
  c('set_timer', 'kick off a pomodoro for me'),
  c('set_timer', 'timer ninety seconds'),
  c('set_timer', 'i\'m putting the pasta on time eleven minutes for me'),
  c('set_timer', 'ping me in 10 minutes'),
  c('set_timer', 'wake me up in twenty minutes i\'m gonna grab a quick nap'),
  c('set_timer', 'let me know when an hour is up'),
  c('set_timer', 'set me a reminder for 15 minutes from now'),
  c('set_timer', 'tea timer three minutes please'),
  c('set_timer', 'nova two minute timer for my noodles'),
  c('set_timer', 'buzz me in an hour and a half'),
  c('set_timer', 'remind me to take the chicken out in 20 minutes'),
  c('set_timer', 'can you give us a shout in five mins'),
  c('set_timer', 'abeg help me time thirty minutes'),
  c('set_timer', 'time me for four minutes i\'m doing planks'),
  c('set_timer', 'in forty minutes tell me to leave for the airport'),
  c('set_timer', 'set an alarm to go off in 12 minutes'),
  c('set_timer', 'put on a one hour timer for the laundry'),
  c('set_timer', 'uh timer for like seven minutes'),
  c('stop_listening', 'okay nova you can sleep now'),
  c('stop_listening', 'nova nova turn your mic off please'),
  c('stop_listening', 'stop listening for a bit i\'m about to jump on a call'),
  c('stop_listening', 'mute your microphone'),
  c('stop_listening', 'take a nap nova'),
  c('stop_listening', 'i need some privacy switch off the listening'),
  c('stop_listening', 'that\'s it for today nova power down the mic'),
  c('stop_listening', 'quit listening to me for now'),
  c('stop_listening', 'disable the mic for a while'),
  c('stop_listening', 'sleep mode nova'),
  c('stop_listening', 'night night nova time to sleep'),
  c('stop_listening', 'stop eavesdropping and switch the mic off'),
  c('open_settings', 'take me to nova\'s settings'),
  c('open_settings', 'i want to change your voice bring up your settings'),
  c('open_settings', 'show me your preferences'),
  c('open_settings', 'pull up your settings so i can change the wake word'),
  c('open_settings', 'open the nova preferences window'),
  c('open_settings', 'i\'d like to slow down how fast you talk can you open your options'),
  c('open_settings', 'bring up the assistant settings panel'),
  c('open_settings', 'get me to the screen where i can pick a different voice for you'),
  c('open_settings', 'open up the options page for nova'),
  c('open_settings', 'open up your settings i want you to have a british accent'),
  c('open_settings', 'nova settings'),
  c('open_settings', 'you sound way too robotic open your voice settings'),
  c('cancel_timer', 'scrap the pasta timer'),
  c('cancel_timer', 'kill the tea timer'),
  c('cancel_timer', 'never mind the timer i already took it out'),
  c('cancel_timer', 'switch that alarm off it\'s driving me mad'),
  c('cancel_timer', 'clear all my timers'),
  c('cancel_timer', 'get rid of the twenty minute timer'),
  c('cancel_timer', 'stop the countdown i don\'t need it anymore'),
  c('cancel_timer', 'call off that reminder you set for me'),
  c('cancel_timer', 'delete the rice timer'),
  c('cancel_timer', 'cancel every timer that\'s running'),
  c('cancel_timer', 'the laundry timer cancel it'),
  c('cancel_timer', 'uh cancel the alarm i set'),
  c('agent_task', 'abeg make claude sort out the login wahala on the website', { agent: 'claude', project: 'website' }),
  c('agent_task', 'have codex write unit tests for all the endpoints in the api', { agent: 'codex', project: 'api' }),
  c('agent_task', 'so like can open code add a dark mode toggle to the website', { agent: 'opencode', project: 'website' }),
  c('agent_task', 'ask claude to refactor the auth middleware in agentic os', { agent: 'claude', project: 'Agentic_OS' }),
  c('agent_task', 'tell the coding agent to bump all the dependencies in the nova repo', { project: 'nova' }),
  c('agent_task', 'uh let codex figure out why the build keeps failing', { agent: 'codex' }),
  c('agent_task', 'send this to opencode rename the utils folder to helpers in the website', { agent: 'opencode', project: 'website' }),
  c('agent_task', 'please let the agent do the needful and write a readme for the api', { project: 'api' }),
  c('agent_task', 'get clawed to migrate the database schema in agentic os', { agent: 'claude', project: 'Agentic_OS' }),
  c('agent_task', 'codex please go through the nova project and strip out the dead code', { agent: 'codex', project: 'nova' }),
  c('agent_task', 'put claude on the flaky websocket tests', { agent: 'claude' }),
  c('agent_task', 'could you get one of the agents to set up ci for the website', { project: 'website' }),
  c('agent_task', 'have open code implement the password reset flow', { agent: 'opencode' }),
  c('agent_task', 'ask code x to speed up the image loading', { agent: 'codex' }),
  c('agent_task', 'let the agent handle adding proper typescript types to the api', { project: 'api' }),
  c('agent_task', 'codex write a migration script that backfills the missing user ids', { agent: 'codex' }),
  c('agent_task', 'hey can claude review my last commit in the nova folder and fix anything dodgy', { agent: 'claude', project: 'nova' }),
  c('agent_task', 'get opencode to convert all the css over to tailwind', { agent: 'opencode' }),
  c('agent_task', 'hand the rate limiting feature off to codex in the api', { agent: 'codex', project: 'api' }),
  c('agent_task', 'have a coding agent scaffold a new settings page for the website', { project: 'website' }),
  c('agent_task', 'get the agent to fix whatever is breaking the tests'),
  c('agent_task', 'in the a genetic os project have claude add logging to the voice module', { agent: 'claude', project: 'Agentic_OS' }),
  c('cancel_task', 'stop claude it\'s going completely off the rails', { agent: 'claude' }),
  c('cancel_task', 'kill the codex job', { agent: 'codex' }),
  c('cancel_task', 'call off the agents'),
  c('cancel_task', 'abort whatever the coding agent is doing'),
  c('cancel_task', 'tell open code to stop working on the website', { agent: 'opencode', project: 'website' }),
  c('cancel_task', 'scrap the agent job on the api', { project: 'api' }),
  c('cancel_task', 'halt all the coding agents right now'),
  c('cancel_task', 'uh pull the plug on the agent that\'s refactoring stuff'),
  c('cancel_task', 'stop the agent that\'s working in agentic os', { project: 'Agentic_OS' }),
  c('cancel_task', 'pull codex off the nova project', { agent: 'codex', project: 'nova' }),
  c('cancel_task', 'terminate the running agent jobs'),
  c('cancel_task', 'i changed my mind cancel the job you gave claude', { agent: 'claude' }),
  c('stop', 'okay okay that\'s enough'),
  c('stop', 'shush'),
  c('stop', 'you can stop talking now thanks'),
  c('stop', 'never mind forget it'),
  c('stop', 'hold on hold on stop'),
  c('stop', 'cut it out nova'),
  c('stop', 'zip it'),
  c('stop', 'quiet please'),
  c('stop', 'stop stop stop'),
  c('stop', 'forget i asked'),
  c('stop', 'alright i get it you can stop now'),
  c('stop', 'oh shut up'),
  c('stop', 'wait wait stop reading that out'),
  c('stop', 'abeg stop'),
  c('stop', 'arre bas bas enough'),
  c('stop', 'stop what you\'re doing'),
  c('confirm_yes', 'yeah go for it'),
  c('confirm_yes', 'yep yep'),
  c('confirm_yes', 'sure thing'),
  c('confirm_yes', 'absolutely do it'),
  c('confirm_yes', 'uh huh yes'),
  c('confirm_yes', 'yes please nova'),
  c('confirm_yes', 'that\'s correct'),
  c('confirm_yes', 'go on then'),
  c('confirm_yes', 'please do'),
  c('confirm_yes', 'affirmative'),
  c('confirm_yes', 'sounds good to me'),
  c('confirm_yes', 'yes o'),
  c('confirm_yes', 'oya go ahead'),
  c('confirm_yes', 'haan yes do it'),
  c('confirm_yes', 'by all means'),
  c('confirm_yes', 'mm hmm that\'s the one'),
  c('confirm_no', 'uh no'),
  c('confirm_no', 'no thanks mate'),
  c('confirm_no', 'nope not that one'),
  c('confirm_no', 'not right now'),
  c('confirm_no', 'hold off on that for now'),
  c('confirm_no', 'no leave it as it is'),
  c('confirm_no', 'i\'d rather you didn\'t'),
  c('confirm_no', 'negative'),
  c('confirm_no', 'nah skip it'),
  c('confirm_no', 'not really'),
  c('confirm_no', 'ah no o'),
  c('confirm_no', 'let\'s not'),
  c('confirm_no', 'no that\'s wrong'),
  c('confirm_no', 'nah i\'m good'),
  c('confirm_no', 'absolutely not'),
  c('confirm_no', 'i don\'t think so'),
  c('chat', 'how do i close an app that\'s frozen on a mac'),
  c('chat', 'so like why does chrome eat so much ram'),
  c('chat', 'should i quit my job and start my own thing'),
  c('chat', 'what\'s the weather looking like in kumasi tomorrow'),
  c('chat', 'um how many minutes are there in a week'),
  c('chat', 'remind me what a closure is in javascript'),
  c('chat', 'what year did ghana get independence'),
  c('chat', 'explain how spotify decides what songs to recommend'),
  c('chat', 'is zoom or teams better for a webinar with like three hundred people'),
  c('chat', 'what\'s 17 percent of 2400'),
  c('chat', 'write me a short poem about rainy mondays'),
  c('chat', 'can you help me word an email to my landlord about the broken boiler'),
  c('chat', 'how do i set up a timer in python'),
  c('chat', 'what\'s the best way to stop procrastinating'),
  c('chat', 'what\'s the difference between notion and obsidian'),
  c('chat', 'recommend me a good podcast about african history'),
  c('chat', 'how do you say thank you in yoruba'),
  c('chat', 'convert five miles to kilometres'),
  c('chat', 'give me a quick recipe for jollof rice'),
  c('chat', 'who won the champions league last season'),
  c('chat', 'explain the difference between a process and a thread'),
  c('chat', 'what camera settings should i use for night shots'),
  c('chat', 'is it gonna chuck it down later'),
  c('chat', 'what time does the sun set today'),
  c('chat', 'tell me something interesting about octopuses'),
  c('chat', 'how long should i boil an egg if i want the yolk runny'),
  c('chat', 'what does docker actually do in simple terms'),
  c('chat', 'summarise the main headlines for me'),
  c('chat', 'can you explain what an api is'),
  c('chat', 'what should i cook tonight i\'ve got chicken peppers and rice'),
  c('chat', 'translate good morning how are you into twi'),
  c('chat', 'give me three birthday gift ideas for my mum'),
  c('chat', 'what are the early symptoms of malaria'),
  c('chat', 'how do i open a bank account in the uk as a student'),
  c('chat', 'what\'s the best time to post on linkedin'),
  c('chat', 'can you rewrite this to sound more professional i want to ask my boss for a raise'),
  c('chat', 'what time zone is lagos in'),
  c('chat', 'who wrote things fall apart'),
  c('chat', 'do you think ai will replace programmers'),
  c('chat', 'kindly explain how compound interest works'),
  c('chat', 'please what is the meaning of ubiquitous'),
  c('chat', 'what day of the week was new year\'s day in 2000'),
  c('chat', 'how many cedis is a hundred dollars now'),
  c('chat', 'abeg how do i remove oil stain from my white shirt'),
  c('chat', 'square root of 729'),
  c('other', 'and he opens the scoring in the twenty third minute what a strike from outside the box'),
  c('other', 'that\'s full time here and it finishes two nil to the black stars'),
  c('other', 'safari rally stage three and he is absolutely flying through the kenyan dust'),
  c('other', 'and that\'s gone all the way for six what a shot'),
  c('other', 'he closes the gap to the leader with three laps to go'),
  c('other', 'timeout called by the coach with forty seconds left on the clock'),
  c('other', 'yes yes yes come on what a goal'),
  c('other', 'both teams look absolutely shattered and there\'s still extra time to come'),
  c('other', 'it\'s twelve o\'clock and you\'re listening to the midday news on joy fm'),
  c('other', 'the president is set to open the new interchange in kumasi on monday'),
  c('other', 'traffic update the motorway is closed between junctions four and five'),
  c('other', 'and for tomorrow expect showers in the morning clearing by the afternoon'),
  c('other', 'open your world with the all new galaxy available in stores now'),
  c('other', 'download the app today from the app store or google play'),
  c('other', 'don\'t touch that dial more hits after these messages'),
  c('other', 'the very notion that this government cares about the youth is laughable'),
  c('other', 'hey guys welcome back to the channel today we\'re gonna open up figma and design a login screen'),
  c('other', 'so what i do at home is i set a timer for twenty minutes and just let the dough rest and that\'s the whole secret'),
  c('other', 'and honestly that\'s the thing you have to know when to quit and when to double down'),
  c('other', 'stop scrolling for a second because this episode is brought to you by our friends at squarespace'),
  c('other', 'the settings on this new camera are unreal let me show you the menu'),
  c('other', 'so in this video i\'ll show you how to close all your apps at once on a mac'),
  c('other', 'chat did you see that clutch i\'m actually cracked'),
  c('other', 'you can\'t just quit on us now not after everything we\'ve been through'),
  c('other', 'we have exactly ten minutes before this whole place goes up'),
  c('other', 'close the gates close the gates they\'re coming'),
  c('other', 'start without me i\'ll join you in a bit'),
  c('other', 'chapter four the door creaked open and she stepped into the dark hallway'),
  c('other', 'once upon a time in a small village there lived a clever spider called kweku ananse'),
  c('other', 'it says here take two tablets every four hours with food'),
  c('other', 'yes i can hear you now sorry my mic was muted'),
  c('other', 'sorry i was on mute go ahead'),
  c('other', 'can you guys see my screen i\'m sharing the figma file now'),
  c('other', 'hey mike yeah the zoom call\'s at four do you have the link'),
  c('other', 'can everyone please mute when you\'re not speaking'),
  c('other', 'okay i\'m gonna stop sharing now and hand over to priya'),
  c('other', 'no mum i\'ve already eaten i promise'),
  c('other', 'i\'ll be there in twenty minutes the traffic on the ring road is crazy'),
  c('other', 'i\'ll ping you on whatsapp after this meeting'),
  c('other', 'yes sir we\'ll have the report on your desk by friday'),
  c('other', 'give me one sec guys i\'ll open the doc and share my screen'),
  c('other', 'let\'s circle back on this next week and close out the ticket'),
  c('other', 'sorry sarah go ahead you were saying'),
  c('other', 'we\'re at terminal two now which gate did you say'),
  c('other', 'babe can you close the window it\'s freezing in here'),
  c('other', 'did you open the slack message i sent you this morning'),
  c('other', 'stop it both of you or there\'s no tv tonight'),
  c('other', 'kids shoes on we\'re leaving in five minutes'),
  c('other', 'go to sleep kofi it\'s way past eleven'),
  c('other', 'stop listening to him he\'s just winding you up'),
  c('other', 'did you remember to set an alarm on your phone we can\'t miss that flight'),
  c('other', 'mum can i have five more minutes on the ipad please'),
  c('other', 'no you can\'t have ice cream before dinner'),
  c('other', 'yes you can go to the party but be home by ten'),
  c('other', 'tell me about your day how was school'),
  c('other', 'ask your dad he knows where the charger is'),
  c('other', 'did you quit spotify premium or are you still paying for it'),
  c('other', 'abeg close that door the generator noise is too much'),
  c('other', 'arre stop it yaar let me finish my work'),
  c('other', 'chale make we go the time dey go'),
  c('other', 'kwame turn that music down i\'m on a call'),
  c('other', 'did you ask claude to review your pr or should i do it'),
  c('other', 'yo tunde codex is down again the whole team is moaning in slack'),
  c('other', 'the timer\'s gone off can you grab the cake out'),
  c('other', 'look at the chrome rims on that car'),
  c('other', 'the clock in the kitchen is five minutes fast don\'t trust it'),
  c('other', 'put your books away it\'s time for dinner'),
  c('other', 'the numbers don\'t add up we\'re short by two hundred cedis'),
  c('other', 'your photos from the wedding came out amazing by the way'),
  c('other', 'did you write the dentist appointment on the calendar on the fridge'),
  c('other', 'i give you my word i\'ll be there'),
  c('other', 'my dad can never find the settings on his phone it\'s hilarious'),
  c('other', 'where did i put my keys ugh i swear they were right here'),
  c('other', 'right so i\'ll set the oven to one eighty and then do the sauce'),
  c('other', 'if i start now i can probably finish before six'),

  // Nova's hands: written by a separate agent that never saw Reflex's data, before any tuning.
  c('system_control', 'abeg reduce the volume small'),
  c('system_control', 'how much charge is remaining on this laptop'),
  c('system_control', 'um switch everything to dark mode my eyes are paining me'),
  c('system_control', 'go ahead and lock up the mac i\'m stepping out'),
  c('media_control', 'stick on some old highlife for me'),
  c('media_control', 'ah this song is like so boring change it'),
  c('media_control', 'who\'s singing this'),
  c('window_control', 'shove chrome over to the right half', { app: 'Google Chrome' }),
  c('window_control', 'kindly shift this window to the external display'),
  c('window_control', 'save how my windows are laid out now and call it deep work'),
  c('window_control', 'uh park whats app in the bottom left corner', { app: 'WhatsApp' }),
  c('files', 'please where is the bank statement pdf i saved last week'),
  c('files', 'give me the gist of the budget excel sheet on my desk top'),
  c('files', 'bin those old screenshots cluttering my downloads'),
  c('files', 'file the march invoice under my accounts folder'),
  c('clipboard', 'remind me what i just copied'),
  c('clipboard', 'grab what you just said so i can paste it somewhere'),
  c('clipboard', 'would you mind putting the link to this article on the clipboard'),
  c('run_shortcut', 'fire off my leaving work shortcut'),
  c('run_shortcut', 'trigger the log expense shortcut with fifty cedis for transport'),
  c('run_shortcut', 'um what short cuts have i got'),
  c('ui_control', 'click the green join button'),
  c('ui_control', 'do command shift t for me'),
  c('ui_control', 'uh take me back up to the top of the page'),
  c('ui_control', 'type happy birthday auntie'),
  c('computer_task', 'this visa application is long just fill the whole thing in with my details'),
  c('computer_task', 'help me buy a data bundle on the mtn website'),
  c('computer_task', 'i was wondering if you could sort me out a ticket to leeds on trainline for saturday'),
  c('other', 'kwame can you hear me now i\'ve turned my volume right up'),
  c('other', 'if you take the shortcut through osu you\'ll beat the traffic'),
  c('other', 'i told him copy the files onto the hard drive before friday'),
  c('chat', 'so how does blue tooth even carry the music to my earbuds'),
];
