/**
 * What Reflex learns from: many ways people phrase each of Nova's intents, beyond the short
 * example lists every engine sees. Placeholders stand for whatever was named - {app},
 * {agent}, {project} - and match utterances where a real name was found and masked.
 * Keys are intent ids (skills and Nova's own); every skill should have an entry.
 * These are matched directly (the closest examples win) and also train Reflex's classifier,
 * together with the patterns in grammar.ts. Never copy a phrasing from the evaluation sets.
 */
export const REFLEX_PHRASES: Record<string, string[]> = {
  open_app: [
    'open {app}', 'open up {app}', 'launch {app}', 'start {app}', 'run {app}', 'fire up {app}', 'bring up {app}', 'pull up {app}', 'switch to {app}',
    'go to {app}', 'show {app}', 'show me {app}', 'get {app} open', 'get {app} up', 'can you open {app}', 'could you launch {app} for me',
    'please open {app}', 'i want to use {app}', 'i need {app}', "let's open {app}", 'load {app}', 'boot up {app}', 'open the {app} app',
    'take me to {app}', 'jump to {app}', 'put {app} on the screen', 'bring {app} to the front', 'focus {app}', 'start up {app}', 'open {app} please',
    'hey open {app}', 'can i get {app}', 'open an app', 'launch an application', 'open the {app} application', 'can you bring up {app}',
    'open {app} for me', 'could you open {app}', 'would you open {app}', 'go ahead and open {app}', 'open {app} real quick', 'launch {app} please',
    'start {app} for me', 'get {app} going', 'get {app} started', 'can you get {app} started', 'bring {app} up', 'pull {app} up',
    'pull up {app} for me', 'i want {app}', 'i want {app} open', 'i need {app} open', 'i need to use {app}', 'i need to get into {app}',
    'let me use {app}', 'let me get into {app}', 'take me into {app}', 'go into {app}', 'switch over to {app}', 'change to {app}',
    'move over to {app}', 'can we open {app}', 'can we go to {app}', "let's go to {app}", "let's use {app}", 'time to open {app}',
    'open {app} i need to reply to someone', 'open {app} i have a call in five minutes', 'open {app} so i can take some notes',
    'open {app} i want to listen to something', 'open {app} i need to send an email', 'launch {app} for my meeting', 'open up {app} for me please',
    'um open {app}', 'uh launch {app}', 'okay so open {app}', 'right, open {app}', 'open open {app}', 'open the {app}', 'launch the {app}',
    'start the {app} app', 'bring the {app} app up', 'open my {app}', 'show me my {app}', 'get me {app}', 'gimme {app}', 'give me {app}',
    '{app} please', '{app} open please', 'open {app} now', 'open {app} again', 'reopen {app}', 'open {app} back up', 'relaunch {app}',
    'can you pull {app} up', 'could you bring up {app} please', 'would you mind opening {app}', 'mind opening {app}', 'please could you open {app}',
    'please can you open {app} for me', 'kindly open {app}', 'abeg open {app}', 'show {app} on the screen', 'display {app}', 'i want to see {app}',
    'i wanna use {app}', 'i wanna open {app}', 'can i use {app}', 'fire {app} up', 'start {app} up', 'boot {app}', 'bring {app} forward',
    'put {app} in front', 'open the app called {app}', 'go ahead and launch {app}', 'i need to check something in {app}, open it',
    'open {app} i need to look at something', 'quickly open {app}', 'open {app} on this mac', 'get into {app} for me', 'hop over to {app}',
    'show me the {app} window', 'put {app} up on the screen', 'bring me to {app}', 'can you switch me to {app}', 'go over to {app}',
    'navigate to {app}', 'i want to go to {app}',
  ],
  quit_app: [
    'quit {app}', 'close {app}', 'exit {app}', 'shut down {app}', 'kill {app}', 'force quit {app}', 'close the {app} app', 'shut {app}', 'end {app}',
    'close out of {app}', "i'm done with {app}", 'turn off {app}', 'quit out of {app}', 'please close {app}', 'can you quit {app}',
    'close {app} for me', 'get out of {app}', 'stop {app} running', 'make {app} quit', 'close that app', 'quit an application', 'close the app',
    'shut the app down', 'dismiss {app}', 'get rid of {app}', 'shut {app} down', 'close {app} now', 'close {app} please', 'please quit {app}',
    'quit {app} now', 'quit {app} for me', 'could you close {app}', 'would you quit {app}', 'can you close {app} please', 'shut {app} please',
    'shut down {app} please', 'kill {app} please', 'exit {app} please', 'close down {app}', 'close {app} completely', 'quit {app} completely',
    'fully quit {app}', 'force close {app}', 'force quit {app} please', '{app} is frozen, close it', "{app} isn't responding, quit it",
    '{app} is stuck, kill it', "i'm finished with {app}", 'no more {app}, close it', 'close {app} i am done', 'quit {app} i am finished',
    'get {app} closed', 'get {app} off my screen', 'close the {app}', 'quit the {app}', 'close my {app}', 'quit my {app}', 'close {app} down',
    'turn {app} off', 'switch {app} off', 'stop {app}', 'terminate {app}', 'kill off {app}', 'close {app} it is using too much memory',
    "close {app} it's draining my battery", 'quit {app} before the meeting', 'i want {app} gone', '{app} can go', '{app} has to go',
    'close out {app}', 'close {app} app', 'quit {app} app', 'please shut {app} down', 'abeg close {app}', 'kindly close {app}', 'shut that app',
    'quit this app', 'close this app', 'close {app} now please', 'could you shut {app}', 'exit from {app}', 'leave {app} and close it',
    'quit out {app}', 'close {app} for good', 'shut {app} off', 'kill the {app} app', 'end the {app} app', 'quit {app} it keeps crashing',
    'close {app} i do not need it',
  ],
  tell_time: [
    'what time is it', "what's the time", 'tell me the time', 'time please', "what's the time now", 'do you have the time', 'what time is it now',
    'current time', 'give me the time', "what's the date", "what's today's date", 'what date is it', 'what day is it today', 'which day is it',
    "what's the day today", 'what month is it', 'what year is it', 'what is the date today', 'tell me the date', 'is it late', 'what hour is it',
    'can you tell me the time', 'what time do you have', "today's date please", 'is it morning yet', 'is it evening already', 'is it still early',
    'is it the afternoon', 'what time is it please', 'what time is it right now', 'what is the time', 'what is the time now', 'the time', 'time now',
    'time please nova', "what's the time please", 'tell me the time please', 'could you tell me the time', 'can you give me the time',
    'what time do we have', "what's the time at the moment", 'what time is it currently', "what's the hour", 'how late is it now', 'how early is it',
    'is it late already', 'is it noon yet', 'is it lunchtime', 'is it midnight yet', 'is it still morning', 'is it night already', 'is it after five',
    'is it past ten', 'is it before noon', 'what day is it', "what's today", 'what is today', 'what day are we on', 'which day are we',
    'is today monday', 'is today saturday', 'is it tuesday', 'is it wednesday today', 'what date is it today', "what's the date please",
    "what's today's date please", 'today is what day', 'what is the date', 'date please', 'the date today', "what's the month", 'which month is it',
    'what year are we in', "what's the year", 'which year is it', 'what week is it', 'what is the date and time', 'time and date please',
    'give me the date and time', 'current date', 'current date and time', "today's date", 'is it the weekend', 'is it a weekday',
    'please what is the time', 'please what time is it', 'excuse me what time is it', 'hey what time is it', 'nova what time is it',
    'what time have you got', 'what o clock is it', 'how is the time', 'what time is it now please', 'tell me the day', "what's the day",
    'tell me what day it is today', 'say the time', 'the time now please', 'how far is the time', 'what day is tomorrow', 'what was yesterday',
    'is it morning or evening', 'is it am or pm', 'what time is it by you', 'the time right now', 'is it october already', 'what month is this',
    'is it still the morning', 'what hour are we at', 'tell me the time now',
  ],
  set_timer: [
    'set a timer for 5 minutes', 'timer for 10 minutes', 'start a 3 minute timer', 'set a 20 second timer', 'remind me in 15 minutes',
    'countdown 2 minutes', 'start a countdown for one minute', 'time me for 30 seconds', 'set an alarm in an hour', 'alert me in 45 minutes',
    'tell me when 10 minutes are up', 'put a timer on for 8 minutes', 'timer 90 seconds', 'can you time 4 minutes', 'wake me up in half an hour',
    'remind me in a minute', 'set a timer', 'i need a timer for twelve minutes', 'notify me in 25 minutes', 'start a timer',
    'set a timer for an hour and a half', 'give me a ten minute timer', 'count down 60 seconds', 'let me know in five minutes',
    'give me a reminder in an hour', 'set me a timer', 'can you set a timer for me', 'set a timer please', 'start a timer for me', 'i need a timer',
    'timer please', 'ten minute timer', 'five minute timer please', 'a timer for two minutes', 'two minutes timer', 'countdown from ten minutes',
    'start counting down from five minutes', 'begin a countdown', 'start the countdown', 'do a five minute countdown', 'time this for three minutes',
    'time the pasta for eleven minutes', 'time the rice for fifteen minutes', 'set a timer for the tea', 'set a timer for my workout',
    'set a timer for the laundry, forty minutes', 'remind me in five minutes', 'remind me in 20 minutes to call my mum',
    'remind me in an hour to check my email', 'remind me in half an hour to move the car', 'alert me in ten minutes', 'ping me in twenty minutes',
    'nudge me in five minutes', 'buzz me in fifteen minutes', 'call me in an hour', 'wake me up in twenty minutes', 'wake me in an hour',
    'give me a heads up in 10 minutes', 'let me know in fifteen minutes', 'tell me when five minutes have passed',
    'let me know when ten minutes are over', 'set an alarm for twenty minutes', 'alarm in 30 minutes', 'set a reminder in ten minutes',
    'start a pomodoro timer', 'pomodoro please', 'twenty five minute focus timer', 'start a focus session for 25 minutes',
    'start a break timer for five minutes', 'a quick one minute timer', 'set a timer for 1 hour 30 minutes', 'set a timer for two and a half minutes',
    'timer for 20 secs', 'set a 3 min timer', 'set timer for 5 mins', 'can you count down 30 seconds for me', 'give me two minutes on the clock',
    'put two minutes on the clock', 'time my run for 20 minutes', 'track ten minutes for me', 'remind me to take the cake out in 35 minutes',
    'in ten minutes remind me to check the stove', 'after twenty minutes tell me to stretch', 'set a countdown for the meeting in fifteen minutes',
    'let me know after an hour', 'ring me in ten minutes', 'warn me in five minutes', 'notify me after 45 minutes', 'a timer of seven minutes please',
    'can i get a timer for twelve minutes', 'start a six minute timer', 'hour timer please', 'thirty minute timer', 'set a half hour timer',
    'start a pomodoro session', 'begin a pomodoro', 'pomodoro for 25 minutes', 'time my talk for ten minutes', 'time my workout for 30 minutes',
    'time my speech for three minutes', 'give me a ten minute countdown for my break',
  ],
  stop_listening: [
    'stop listening', 'stop listening to me', 'go to sleep', 'sleep now', 'turn off the microphone', 'turn the mic off', 'mute yourself',
    'mute the mic', "don't listen", 'stop the microphone', 'you can go to sleep', 'pause the microphone', 'mic off please', 'switch off your mic',
    'stop recording me', 'disable listening', 'take a break from listening', 'turn off listening', "that's all for now, stop listening",
    'close your ears', 'stop the mic', 'go to sleep now', 'no more listening', 'stop listening please', 'stop listening now',
    'stop listening for a while', 'you can stop listening', 'please stop listening', 'stop listening to us', 'quit listening',
    'no more listening please', "don't listen to me now", "don't listen anymore", "don't listen for now", 'stop recording', 'stop recording please',
    'turn your microphone off', 'turn off your mic please', 'switch your mic off', 'switch off your microphone', 'mic off now',
    'turn the microphone off please', 'disable the microphone', 'disable the mic', 'shut off the mic', 'shut your mic off', 'kill the mic',
    'close the mic', 'mute your microphone', 'mute please', 'go mute', 'mute nova', 'pause listening please', 'pause your microphone',
    'go to sleep nova', 'sleep nova', 'time to sleep', 'you can go to sleep now', 'go back to sleep', 'go offline', 'stop paying attention',
    "that's all, go to sleep", "that's it for now, mic off", "we're done, stop listening", "i'm done, you can sleep", 'you can take a break now',
    'stop listening until i call you', "don't listen until i say your name", 'switch off listening', 'turn listening off', 'hang up the mic',
    'microphone off please', 'no more mic', 'deafen yourself', 'cover your ears nova',
  ],
  open_settings: [
    'open settings', 'open your settings', 'show settings', 'show your settings', 'open preferences', 'open your preferences', 'settings please',
    'go to settings', 'i want to change a setting', 'change your settings', 'open the settings window', 'show me the configuration',
    'open configuration', 'open config', 'change your voice', 'change the wake word', 'adjust your preferences', 'where can i change the settings',
    'bring up your settings', 'i want to configure you', 'your settings', 'open the settings', 'open settings please', 'show the settings',
    'show me settings', 'open up settings', 'bring up settings', 'pull up your settings', 'go to your settings', 'take me to settings please',
    'open your options', 'show your options', 'open the options', 'open your config please', 'show me your config', 'open the configuration',
    'open nova preferences', "open nova's settings", 'open assistant settings', 'show assistant settings', 'i want to adjust your settings',
    'i need to change a setting', 'let me change your settings', 'let me change your voice', 'i want to change your voice',
    'change your voice please', 'i want a different voice', 'i want to rename you', 'change your name', 'i want to change your name',
    'i want a new wake word', 'change how fast you talk', 'change your speaking speed', 'change the orb colors', 'change your appearance',
    'i want to change the theme', 'configure nova', 'open setup', "where's your settings page", 'how do i get to your settings',
    'where can i configure you', 'settings window please', 'preferences please', 'open the settings screen', 'let me tweak your settings',
    'i want to pick another voice', 'show me where to change your voice', 'let me set you up', 'open your control panel', 'go to preferences',
    'let me look at your settings', 'i want to see your options', 'show me what settings you have', 'what settings do you have, open them',
    'open where i can change your settings',
  ],
  cancel_timer: [
    'cancel the timer', 'stop the timer', 'clear the timers', 'cancel my timer', 'turn off the timer', 'delete the timer', 'remove my timers',
    'end the timer', 'stop the countdown', 'cancel the countdown', 'cancel all timers', 'never mind the timer', 'kill my timers', 'abort the timer',
    "i don't need the timer anymore", 'switch off the alarm', 'cancel the alarm', 'stop the alarm', 'get rid of the timer', 'forget the timer',
    'no more timer', 'clear my countdown', 'cancel the countdown timer', 'stop all timers', 'cancel timer', 'cancel timers', 'cancel the timers',
    'cancel my timers', 'stop my timer', 'stop the timers', 'stop timer', 'end my timer', 'end the countdown', 'clear timers', 'clear my timers',
    'clear the countdown', 'delete my timer', 'delete the countdown', 'remove the timer', 'remove all timers', 'turn off my timers',
    'switch off the timer', 'kill the countdown', 'abort my timer', 'drop the timer', 'forget my timer', 'forget the countdown',
    "i don't need the countdown", 'no timer please', 'no need for the timer', 'never mind my timer', 'the timer can go', 'cancel the alarm please',
    'stop the alarm please', 'turn off the alarm', 'dismiss the timer', 'dismiss the alarm', 'silence the timer', 'cancel the reminder',
    'cancel my reminders', 'stop the reminder', 'cancel the five minute timer', 'stop the ten minute countdown', 'cancel the pasta timer',
    'cancel the tea timer', 'cancel all my countdowns', 'stop counting down', 'call off the timer', 'scrap the timer',
    'the countdown is not needed anymore', 'turn the countdown off',
  ],
  agent_task: [
    'ask {agent} to fix the failing test in {project}', 'have {agent} add a readme to {project}', 'tell {agent} to refactor the login page',
    'get {agent} to write tests for the api', 'ask the agent to update the docs in {project}', 'can you have {agent} clean up this repo',
    '{agent} fix the bug in {project}', 'let {agent} handle the migration in {project}', 'ask {agent} to add a dark mode',
    'have {agent} upgrade the dependencies', 'get {agent} to review the code in {project}', 'tell {agent} to implement the search feature',
    'ask {agent} to write documentation for {project}', 'have the agent fix the build', 'put {agent} on the failing tests',
    '{agent} please add logging to {project}', 'can {agent} rename the variables in {project}', 'tell the agent to create a new component',
    'ask {agent} to set up ci for {project}', 'get the agent to optimize the images', 'have {agent} delete the unused files in {project}',
    'ask {agent} to make the tests pass', 'tell {agent} to commit the changes', 'let the agent work on {project}',
    'get {agent} working on the landing page', 'i want {agent} to fix the css in {project}', 'send {agent} to fix the crash',
    '{agent} add a feature to {project}', '{agent} write a script that renames files', 'ask {agent} to take a look at the failing tests',
    'have {agent} look into the crash in {project}', 'can you get {agent} to fix this bug', '{agent} can you fix the tests in {project}',
    '{agent} please fix the build', '{agent}, i need you to add a login page to {project}', 'let {agent} take care of the refactor',
    'get {agent} on the bug in {project}', 'tell {agent} to make the tests green', 'ask {agent} to write me a script that cleans up my downloads',
    'have {agent} build a small landing page in {project}', 'ask the coding agent to fix the linting errors',
    'get the agent to write the tests for {project}', 'can the agent update the packages in {project}', 'i want the agent to refactor the api layer',
    'tell {agent} i want the button to be blue in {project}', 'ask {agent} to implement the new design in {project}',
    'send this to {agent}, fix the header alignment', 'give {agent} the job of cleaning up {project}', 'assign {agent} to fix the login flow',
    "{agent} there's a bug in {project}, fix it", 'hand the migration over to {agent}', 'have {agent} write a readme for {project}',
    'get {agent} to run the tests and fix what fails in {project}', 'ask {agent} to profile the slow page in {project}',
    'have {agent} add types to {project}', 'tell {agent} to convert {project} to typescript', 'have {agent} set up the database for {project}',
    'ask {agent} to create a new branch and fix the bug', 'tell {agent} to push the changes', 'have {agent} squash the commits in {project}',
    'get {agent} to add a settings screen to {project}', 'ask {agent} to make the app work offline',
    'have the agent generate test data for {project}', 'tell {agent} to add a footer to the site', 'can {agent} build me a todo app in {project}',
    '{agent} write a function that parses dates', 'ask {agent} to explain and then fix the error in {project}',
    'get {agent} to clean up the git history', 'let {agent} deal with the merge conflicts in {project}',
  ],
  cancel_task: [
    'stop the agent', 'cancel the agent task', 'tell the agent to stop', 'stop {agent} working', 'make {agent} stop', 'cancel {agent}',
    'tell {agent} to stop', 'abort the task', 'kill the agent', 'stop what {agent} is doing', 'halt {agent}', 'cancel the job', '{agent} stop',
    'call off the agent', 'stop the coding task', "end the agent's task", 'tell {agent} to cancel', 'make the agent stop working',
    'stop the agent task', 'cancel the agent', '{agent} cancel that task', 'the agent should stop now', 'stop the agents', 'stop all agents',
    'cancel all agent tasks', 'cancel the agents', 'abort the agents', 'kill all the agents', 'stop the coding agents', 'stop the agent please',
    'please stop the agent', 'cancel the task please', 'cancel the running task', 'stop the running task', 'abort the running job', 'end the task',
    'end all tasks', 'stop {agent} now', 'stop {agent} please', '{agent} stop working', '{agent} halt', '{agent} cancel',
    '{agent} stop what you are doing', '{agent} drop it', 'tell {agent} to drop it', 'tell {agent} to stop working', 'ask {agent} to cancel',
    "cancel {agent}'s job", "stop {agent}'s task", 'make {agent} quit', 'kill {agent}', 'pause the agent', '{agent} should stop now',
    "the agent doesn't need to continue", 'call off the task', 'call the agent off', 'no more agent work', 'cancel the coding job',
    'stop the agent job', 'tell the agents to stop', 'the coding task can stop', 'abort {agent}', 'halt the task',
  ],
  stop: [
    'stop', 'never mind', 'cancel that', 'be quiet', 'shut up', 'forget it', 'stop talking', 'quiet', 'silence', 'enough', 'okay stop', 'stop it',
    "that's all", 'never mind that', 'forget that', 'hold on stop', 'stop speaking', 'shh', 'that will do', 'please stop', 'no stop', 'stop stop',
    'enough talking', 'cancel', 'stop now', 'stop please nova', 'nova stop', 'okay nova stop', 'hey stop', 'stop that', 'stop that please',
    'stop talking now', 'please stop talking', 'stop speaking now', "that's enough thanks", "that's enough nova", 'enough now', 'enough thanks',
    'alright stop', 'alright enough', 'okay enough', 'okay thank you', 'okay thanks', "thanks that's all", "that's all thanks", "that's all i needed",
    'i got it thanks', 'got it, stop', 'got it thank you', 'no need to continue', "you don't have to finish", "don't finish that", 'skip that',
    'cancel that please', 'forget about it', 'forget it nova', 'never mind nova', 'nevermind', 'nah never mind', 'actually never mind',
    'oh never mind', 'wait never mind', 'hold on', 'hold on a second', 'wait wait', 'wait stop', 'pause', 'pause please', 'be quiet please',
    'be quiet nova', 'quiet down', 'quiet now', 'hush now', 'shh shh', 'silence please', 'shut up nova', 'zip it', 'stop it now', 'halt',
    'okay that will do', "that's plenty", 'ok stop there', 'stop right there', 'shush please', 'shh please', 'shh nova', 'hush please', 'pipe down',
    'knock it off', 'quiet quiet', 'that is enough now', 'forget it, stop', 'no forget it', 'forget about that, never mind',
  ],
  confirm_yes: [
    'yes', 'yeah', 'yeah do it', 'go ahead', 'confirm', 'sure', 'okay do it', 'yes please do', 'yep', 'correct', "that's correct", 'please do',
    'go for it', 'absolutely yes', 'of course', 'definitely', 'ok', 'alright', 'fine go ahead', 'yes go ahead', 'sounds good', 'proceed', 'allow it',
    'approved', 'yes allow it', 'let it', 'go on', 'yes do that', 'yup', 'right', 'uh huh yes', 'yes please', 'yes do it', 'yeah go ahead',
    'yeah do that', 'yeah please', 'yep go ahead', 'yep do it', 'yup go ahead', 'sure go ahead', 'sure do it', 'ok go ahead', 'okay do that',
    'okay sure', 'okay yes', 'alright go ahead', 'alright then', 'fine', 'fine do it', "that's fine", 'that is correct', 'right, do it', 'exactly',
    'absolutely, go ahead', 'certainly', 'please do it', 'please proceed', 'go ahead then', 'go ahead please', 'do it now', 'do it please', 'do it',
    'make it happen', "let's do it", "let's go", 'sounds good to me', 'sounds great', 'that works', 'perfect', 'great, go ahead', 'good, do it',
    'yes i am sure', "yes i'm sure", 'yes confirm', 'confirmed', 'i confirm', 'approve', 'allow', 'yes allow', 'you can', 'you may',
    'you can go ahead', 'permission granted', 'aye', 'yes sir', 'yes boss', 'oh yes', 'mm hmm yes', 'yeah yeah go on', 'yes yes do it', 'why not',
    'yes that one', 'yes exactly', 'yes please go on', 'sure, go on', 'yeah alright', 'okay fine', 'totally', 'for sure', 'yes of course',
  ],
  confirm_no: [
    'no', "don't", 'no thanks', 'leave it', 'abort', 'no no', "no don't", "don't do it", 'cancel it', 'no way', 'deny', "don't allow it", 'refuse',
    'definitely not', 'not yet', 'skip it', 'leave it alone', 'no thank you', 'decline', 'better not', "don't bother", 'nope not that', 'wait no',
    'no please', 'nope, leave it', 'nah thanks', 'no leave it', 'no keep it open', 'no, not now', 'not now thanks', 'maybe later', 'later',
    'not today', 'no need', 'no need thanks', "no don't do that", "please don't do that", "don't touch it", "don't close it", "don't quit it",
    'leave it be', 'leave it open', 'keep it', 'keep it running', 'no wait', 'hold on no', 'hold off on that', 'not that', 'not that one', 'wrong',
    "that's wrong", "that's not what i said", 'changed my mind', 'actually no', "no i don't want that", "i don't want that", 'rather not',
    "i'd rather not", 'denied', 'reject', 'disallow', 'not allowed', 'certainly not', 'of course not', 'never', 'nope nope', 'no sir',
    'no not at all', 'not at all', 'no, stop that', 'no, never mind', 'no, wrong one', 'no no, leave it', 'nah not now', "no, don't bother",
    'negative', 'negative, leave it', 'no, negative',
  ],
  chat: [
    'what is the capital of france', 'explain how photosynthesis works', 'tell me about the roman empire', 'how do i boil an egg',
    'write a haiku about the ocean', 'summarise this idea for me', 'help me think through a decision', 'who invented the telephone',
    'what does http stand for', 'how far away is the moon', 'give me a recipe for pancakes', "what's a good name for a cat",
    'translate good morning into french', 'what is machine learning', 'why do cats purr', 'how many people live in lagos', 'recommend a good book',
    'what should i cook tonight', 'draft an email to my manager', 'tell me something interesting', 'can you explain recursion',
    'how does a car engine work', 'who is the president of ghana', 'compare python and javascript', "what's the square root of 144",
    'give me three ideas for a birthday party', 'ask {agent} what a monad is', 'ask {agent} how to center a div', '{agent} what does this error mean',
    "what's the best way to learn guitar", 'is coffee bad for you', 'tell me a story', 'how tall is mount kilimanjaro',
    'what language do they speak in brazil', 'define entropy', 'what are black holes', 'how do planes stay in the air', 'give me a fun fact',
    'what is the population of accra', 'write a short thank you note', 'why is the ocean salty', 'why are leaves green',
    'how many legs does a spider have', 'how much does a car cost', 'how long does it take to boil rice', 'how old is the universe',
    "what's the difference between a virus and bacteria", 'who wrote romeo and juliet', 'who was nelson mandela', 'where is timbuktu',
    'when did world war two end', 'which planet is the biggest', 'is it true that goldfish forget things', 'what happens when a star dies',
    "what's 20 percent of 150", 'what is 12 times 7', 'what does ubuntu mean', 'write a poem about the sunset', 'tell me a riddle',
    'give me tips to sleep better', 'how can i improve my english', 'what do you think about electric cars', 'can you help me write a cover letter',
    'suggest a movie for tonight', 'what is the speed of light', 'who discovered penicillin', 'what is the tallest mountain in africa',
    'how many bones are in the human body', 'what causes earthquakes', 'what is inflation', 'how does the stock market work', 'what is bitcoin',
    'who was the first man on the moon', 'what is the largest ocean', 'how hot is the sun', 'what is dna', 'when was the internet invented',
    'what is the population of nigeria', 'what is the capital of kenya', 'what currency does japan use', 'what language is spoken in senegal',
    'how far is kumasi from accra', 'what is the biggest country in the world', 'who is the richest person in the world', 'what does gdp mean',
    'what is climate change', 'why do we have seasons', 'what is gravity', 'how do i reset my password', 'how do i update my mac',
    'how do i connect to wifi', 'how do i make fufu', 'how do i cook waakye', 'how do i tie a tie', 'how do i remove a stain from a shirt',
    'how do i start a business', 'how do i write a cv', 'how do i learn spanish', 'how do i undo a git commit', 'how do i install node',
    'how do i use docker compose', 'how do i make my code faster', 'how do i split a pdf on a mac', 'how do i record my screen on mac',
    'how do i free up space on my mac', 'how do i clear my browser cache', 'write an email asking for a day off', 'draft a reply to my landlord',
    'write a short bio for my linkedin', 'write a birthday message for my friend', 'help me write a speech for a wedding', 'write a poem about ghana',
    'write a product description for a water bottle', 'summarize the history of the roman empire', 'rewrite this sentence to sound more professional',
    'give me a catchy slogan for a bakery', 'write a text to cancel a meeting politely', 'what should i eat for lunch',
    'should i learn python or javascript', 'what is a good gift for my dad', 'how can i be more productive', 'what are some good habits',
    'how do i deal with stress', 'what is a good workout for beginners', 'which phone should i buy', 'is it worth buying a macbook',
    'what do you think about ai', 'what is the best programming language', 'give me ideas for a weekend trip', "what's 25 times 4",
    'what is 100 divided by 7', "what's 18 percent of 250", 'convert 10 miles to kilometers', 'how many ounces in a pound',
    'what is 2 to the power of 10', 'how many seconds in an hour', 'how many days until christmas', 'how many weeks in a year',
    "what's the weather today", 'will it rain today', 'how hot is it outside', 'what is the weather in london', "what's the forecast for tomorrow",
    "what's in the news today", "what's happening in the world", 'any news about the election', 'what is the latest on the football', 'who made you',
    'what is your name', 'are you an ai', 'how are you', 'how are you doing today', 'what can you help me with', 'what are you able to do', 'what kind of things can you do', 'what are you capable of',
    'can you hear me nova', 'are you there', 'are you listening', 'do you understand me', 'thank you', 'thanks nova', 'good morning',
    'good night nova', 'hello', 'hi nova', 'hey there', 'what is slack used for', 'is spotify free', 'how much does figma cost',
    'is chrome better than safari', 'what is xcode', 'how do i use notion', 'what is docker', 'how does zoom make money',
    'what is the difference between mail and outlook', 'how do i set a timer on my phone', 'what is a pomodoro', 'how do alarms work',
    'how do i stop my mac from sleeping', 'how do i quit smoking', 'how do i close a bank account', 'how do i open a bank account',
    'what time zone is ghana in', 'what time is it in new york', 'what time is it in tokyo right now', 'when does the sun rise',
    'why do clocks go forward', 'what does api stand for', 'explain what a neural network is', 'what is the difference between a list and a tuple',
    'how do vaccines protect us', 'why is exercise good for you', 'who is the best footballer of all time', 'what is the meaning of life',
    'tell me a fun fact about ghana', 'how do bees make honey', 'why do onions make you cry', 'what is a good book about habits',
    'can you recommend a laptop under a thousand dollars', 'what are the symptoms of malaria', 'how do i improve my credit score',
    'what is a mortgage', 'how do solar panels work', 'what is the speed of sound', 'who wrote the bible', 'what is the longest river in the world',
    'explain blockchain in simple terms', 'help me name my new puppy', 'what can i cook with rice and eggs', 'how do i negotiate a higher salary',
    'plan a three day trip to cape coast', 'what are the rules of chess', 'teach me a word in french', 'what is the plural of octopus',
    'spell necessary', 'what rhymes with orange', 'is a tomato a fruit', 'why is the moon sometimes visible during the day',
    'how do i know if an egg is fresh', 'what is the best way to study for exams', 'who won the match yesterday',
    'what was the score in the chelsea game', 'when do the black stars play next', 'who is top of the league', 'did arsenal win last night',
    'who scored for ghana', 'when is the world cup final', 'who won the champions league this year', 'will it be hot tomorrow',
    'is it going to be sunny this weekend', 'do i need an umbrella today', 'will it rain in accra this afternoon', "what's the temperature outside",
    'how cold will it get tonight', 'is there a storm coming', 'should i take a jacket today', 'where is the closest pharmacy',
    'how do i get to the airport', 'where can i buy a charger near me', 'find a good restaurant near me', 'where is the nearest atm',
    'how far is the mall from here', 'which way is the train station', 'when did ghana become a republic', 'what year did the first iphone come out',
    'when was nelson mandela released', 'what year did world war one start', 'when was the university of ghana founded',
    'how long ago were the pyramids built', 'help me plan my day', 'help me organize my tasks', 'can you help me prepare for my meeting',
    'plan a healthy meal for the week', 'make me a study schedule', 'help me think of a gift for my wife', 'give me a packing list for a beach trip',
    'help me write a to do list', 'help me prioritize my work', 'which apps are running', 'what apps are open right now',
    'how many apps do i have running', 'is slack still open', "what's running on my mac", 'which app is using the most memory',
    'what programs are open', 'do i have chrome open', 'what season is it', 'how many days are left in the year', 'how many days until the weekend',
    'what do you know about black holes', 'what do you know about the roman empire', 'what do you know about ghana',
    'tell me what you know about volcanoes',
    'does dark mode really save battery', 'is it bad to leave my laptop charging overnight', 'how do i make my mac battery last longer',
    'what does do not disturb actually block', 'why is my wifi so slow at night', 'how does spotlight find my files',
    'what is the difference between minimize and hide on a mac', 'what are some good keyboard shortcuts for a mac',
  ],
  other: [
    'and then he went back to the office', 'did you see the game last night', "i'll call you back later", 'the traffic was terrible this morning',
    'we should get lunch sometime', 'i remember when we used to go to the beach', 'do you remember that trip to cape coast', 'this episode is so good', 'welcome back to the show', 'in other news the markets fell today',
    'can you pass the remote', 'mum is coming over on sunday', "i don't know what she meant", 'that movie was amazing',
    'okay class open your books to page ten', 'the kids are finally asleep', "let's meet at six", 'he said he would be late', "it's raining again",
    'what did you have for dinner', 'turn left at the next junction', 'subscribe to our channel for more videos',
    'thank you for calling customer service', 'the recipe needs two eggs', "i think we're out of milk", 'this is the evening news',
    'and the crowd goes wild', 'hahaha no way', 'yeah yeah i know', 'where did i put my keys', 'uh huh', 'hmm', 'she told me everything',
    'our top story tonight', 'you have to try the new restaurant', 'the meeting got moved to friday', 'can you hear me now',
    'sorry i was on the other call', 'my phone is almost dead', 'they won the championship last year', 'and he scores in the last minute',
    'the referee has blown the whistle', 'coming up after the break', 'here are the headlines', 'police say the suspect has been arrested',
    'the forecast shows rain all weekend', 'stay tuned for more', 'this program is brought to you by', 'i was just telling him about it',
    'my sister called yesterday', 'the baby is crying', "don't forget to bring the charger", 'we are almost there', "i'll be there in ten minutes",
    'that was so funny', 'i know right', 'no way that happened', 'he always does that', 'oh my god look at that', 'can you believe it',
    'my boss wants the report by monday', 'the food is ready come and eat', 'who left the lights on', 'put your shoes on we are late',
    'hello yes i can hear you', 'let me call you back', 'honestly i have no idea', 'the second half starts soon', 'that was a close call',
    'it was nice seeing you', 'good evening and here are the main stories', 'the president arrived in abuja this morning',
    'police are appealing for witnesses', 'the central bank raised interest rates', 'fuel prices are expected to rise again',
    'the government has announced new measures', 'the opposition has rejected the proposal', 'officials say the road will reopen next week',
    'the storm caused flooding in several towns', 'the company reported record profits', 'the cedi fell against the dollar today',
    'health officials are urging people to get vaccinated', 'protesters gathered outside parliament', 'the trial will resume on monday',
    'scientists have discovered a new species', 'the minister declined to comment', 'you are watching the evening news', 'this is the world service',
    'and now the weather', 'here is the sports news', "that's all for tonight's bulletin", 'join us again tomorrow', 'back to you in the studio',
    'our reporter is at the scene', 'more on that story later', 'after the break we look at the markets', 'viewers may find some scenes upsetting',
    'the following is a paid advertisement', 'call now and get fifty percent off', 'offer valid while stocks last', 'terms and conditions apply',
    'available in all good stores', 'brought to you by our sponsors', 'what a save by the goalkeeper', 'the striker hits the post',
    'it is a corner kick', 'the referee shows a yellow card', 'the ball goes out for a throw in', 'that is offside', 'penalty to the home side',
    'the crowd is on its feet', 'they need a goal in the last ten minutes', 'the black stars are through to the final',
    'chelsea lead arsenal one nil', 'what a finish', 'and it goes in off the crossbar', 'he dribbles past two defenders', 'the match ends in a draw',
    'extra time will be played', 'the coach has made a substitution', 'she wins the hundred meters', 'a new world record', 'the fans are singing',
    'the second half is under way', 'hey guys welcome back to my channel', "today we're going to talk about productivity",
    'if you enjoyed this video hit the like button', 'let me know in the comments', "and that's it for today's episode",
    "on today's podcast we're joined by a special guest", 'this episode is sponsored by', 'use my code for ten percent off',
    'see you in the next one', 'so as you can see here', 'let me share my screen', "in this tutorial i'll show you",
    'first you want to open the settings on your phone', 'now click on the start button', 'then close the lid and wait',
    'set the oven to two hundred degrees', 'leave it for about twenty minutes', 'stir it every five minutes', "hi, it's me",
    "i'm calling about the invoice", "sorry, i didn't catch that", 'can you repeat that please', "you're breaking up", "i think you're frozen",
    'can you mute yourself please', 'who just joined', 'let me add him to the call', 'can we push the meeting to tomorrow',
    "let's circle back on that", 'any questions before we wrap up', "i'll share the slides after the call", 'next slide please',
    "that's a good point", 'i agree with you', 'let me check and get back to you', 'send me the link', 'i will email you the details',
    'are we still on for friday', 'the client wants changes', 'the deadline is next week', 'we need to hire another developer',
    'the server went down last night', 'the tests passed on my machine', "i'll review your pull request later", 'can you send me the api key',
    'who broke the build', 'where did you put the car keys', 'have you seen my glasses', 'dinner is ready', 'come and eat', 'wash your hands',
    'go and brush your teeth', 'time for bed', "it's time to go to school", 'hurry up we are late', 'turn off the tv and come to bed',
    'close the fridge', 'shut the door', "don't slam the door", 'open the gate for the driver', 'the water is boiling', 'the rice is burning',
    'somebody is at the door', 'the light has gone off', 'dumsor again', 'the generator is making noise', 'the baby needs changing',
    'feed the dog please', 'did you lock the front door', 'who finished the milk', "i'm going to the market", 'buy bread on your way back',
    'bring me some water', 'pass me my phone', 'can you help me carry this', "i'm tired", "i'm so hungry", 'what are we eating tonight',
    'what time are we leaving for church', 'what time does the party start', 'what time is your flight', 'when are you coming back',
    'what time will you be home', 'are you awake', 'did you sleep well', 'good morning mummy', 'good night everyone', 'see you tomorrow',
    'take care of yourself', 'call me when you get there', 'tell your sister i said hi', 'ask your mum if she wants tea', 'tell him to wait for me',
    'stop teasing your brother', "don't touch that", 'stop jumping on the bed', 'quit whining', 'set the house alarm before you leave',
    'the timer on the oven went off', 'the alarm is ringing downstairs', "my alarm didn't go off this morning", 'slack notifications are so annoying',
    'i hate zoom meetings', 'spotify keeps crashing on my phone', 'my chrome has too many tabs', "i'll send it on whatsapp", 'check your email',
    'i sent you a message on teams', 'she shared the figma file', 'the notion page is out of date', 'we moved everything to notion',
    'download it from the app store', 'i deleted whatsapp last week', 'my calendar is full today', 'my phone is on silent', 'i closed all my tabs',
    'i opened the file yesterday', 'he never closes his apps', 'the settings reset after the update', 'my mac is so slow today',
    'this laptop is getting hot', 'where did i put that file', 'hmm let me think', 'what was i doing', 'okay where was i', 'oh no i forgot',
    'this is so annoying', 'oh that makes sense', 'wait what', 'huh interesting', 'let me see', 'come on', 'yes finally it works', 'oh no not again',
    'yes mummy', 'no daddy', "yes i'm listening to you", 'no i did not take it', 'yeah we are ready', 'no we are not going', 'okay i am coming',
    'stop it, both of you', 'stop crying my dear', "we'll start in five minutes", 'the meeting starts at ten', 'what time did the match end',
    "they'll be here in twenty minutes", 'give me two seconds', 'hold on let me find it', "it's quarter past six", 'the train leaves at nine',
    'close your eyes and make a wish', 'open your mouth wide', 'turn the music down', 'turn up the volume on the tv', 'put the kettle on',
    'switch off the fan', 'the kids are watching a movie', 'she opened a new shop', 'he quit his job last month', 'they closed the road for repairs',
    'the settings on my phone are weird', 'my timer app is broken', 'i forgot to cancel my subscription', 'our wifi is so slow',
    'the printer is out of ink', 'are you still on the call', 'your camera is off', 'i can see you now', 'let us pray',
    'please rise for the national anthem', 'the service starts at eight', 'ladies and gentlemen welcome aboard', 'please fasten your seatbelts',
    'the next stop is circle', 'mind the gap', 'your order is ready', 'table for two please', 'can i get the bill', 'keep the change',
    'thank you for listening', 'thanks for watching everyone', "that's all for this week's episode",
    'you can listen to the full interview on our website', 'subscribe wherever you get your podcasts', 'follow us for more',
    'hit the bell icon so you never miss a video', 'drop a comment below', 'you have been listening to the morning show',
    'we will be right back after this short break', 'stay tuned', 'the podcast is available on all platforms', 'listen live on our app',
    "don't forget to share this video", 'remember to like this post', 'can you unmute yourself', 'i think my mic is muted', 'sorry i was on mute',
    'wait a minute let me check', 'just a minute please', 'one minute, i am coming', 'give me five minutes to get ready', 'hold on a minute',
    'in a minute darling', 'my netflix subscription renews tomorrow', 'spotify premium is too expensive', 'i forgot to close the tabs yesterday',
    'he left zoom running all night', 'slack was down this morning', 'chrome is eating my memory', 'my whatsapp is not delivering messages',
    'teams keeps logging me out', 'the zoom link is in the invite', 'i will share my screen on zoom', 'notion is really good for notes',
    'figma crashed and i lost my work', 'what are you doing this weekend', 'are you hungry dear', 'did you finish your homework',
    'where are you going', 'how was school today', 'when is your exam', 'what did the doctor say', 'have you eaten', 'are you coming with us',
    'is it your turn to drive', 'can you help your brother', 'do you want some tea', 'tomorrow will be mostly cloudy with a chance of rain',
    'expect showers in the afternoon', 'temperatures will reach thirty degrees', 'a heat wave is expected this week',
    'the markets closed higher today', 'oil prices dropped this morning', 'over to you in the newsroom', 'and in sports news tonight',
    'the league table after this weekend', 'the black stars beat nigeria two one', 'no i am not tired', 'yes i already ate', 'no she is not here',
    'yes he called this morning',
    'i moved all the photos to my laptop yesterday', 'she deleted the whole folder by accident', 'he renamed the file and now nobody can find it',
    'i saved the document on the desktop somewhere', 'did you open the attachment i sent', 'tap the link in my message when you get a chance',
    'the button on their website is not working', 'i clicked the wrong thing and it logged me out', 'i love this song so much', 'this album takes me back',
    'this track is a banger', 'the volume on this tv is too low', 'my screen cracked last week', 'the battery on my phone is dying',
    'i always leave my laptop open overnight', 'close the curtains and the windows before you go', 'my brother keeps skipping school',
    'we skipped the queue at the airport', 'she typed the whole essay in one night', 'he copied my answers in the exam',
  ],
  remember: [
    'remember to pick up the dry cleaning',
    'remember that my standup is at ten', "remember my wife's birthday is in june", "remember that i'm vegetarian", 'remember i prefer short answers',
    "don't forget that the office closes early on fridays", 'note that the api key rotates every month', 'make a note that the client is called acme',
    'keep in mind that i work from home on mondays', 'please remember my car is a blue toyota', 'save this, my flight is on tuesday',
    "remember that my manager's name is kofi", 'remember that i like my coffee black', 'remember the meeting room is on the third floor',
    'can you remember that my gym days are tuesday and thursday', 'remember my daughter starts school at seven',
    'note down that the deadline is friday', "don't forget i'm allergic to peanuts", "keep in mind that i don't eat pork",
    'remember this for me, the parking spot is number twelve', 'nova remember that my sister lives in kumasi', 'remember that i use a mac at work',
    'could you remember that my dentist is on tuesday', "don't forget my mum's birthday is on the fifth", "don't forget the rent is due on the first",
    "don't forget i'm on leave next week", 'keep in mind my team meets on wednesdays', 'keep in mind my laptop is a macbook pro',
    'remember my password manager is 1password', 'remember i take the bus to work', "don't forget my son's name is kwame",
  ],
  recall: [
    'what do you remember about me', 'what do you know about me', 'what have i told you about myself', 'do you remember my birthday',
    'what did i tell you about my standup', "what's my manager's name again", 'do you remember what i said about the deadline',
    'tell me what you remember', 'what do you have in your memory', 'what do you remember about my schedule', 'what are my gym days again',
    'do you know when my flight is', 'have i told you about my car', 'what do you remember', 'what did i ask you to remember',
    'remind me what i told you about the wifi', 'what do you know about my family', 'do you remember where the meeting room is',
    'do you remember when my dentist appointment is', 'do you remember what my car is', 'do you remember where i work',
    "do you remember my sister's name", 'did i tell you when my flight is', 'did i tell you my gym days', "do you know my manager's name",
    'can you recall what i said about the rent', "do you recall my son's name", 'when is my dentist appointment again',
    'where did i say the meeting room is', 'what did i say my car was',
  ],
  forget: [
    'forget that my standup is at ten', 'forget what i told you about my car', 'forget my old address', 'delete the memory about the wifi',
    'please forget what i said about the deadline', "you can forget that i'm vegetarian", 'erase what you know about my flight',
    'remove the note about the office', 'stop remembering my gym days', 'forget everything about my manager', 'delete what you remember about my car',
    'forget the note about the parking spot',
  ],
  undo: [
    'undo that', 'undo', 'take that back', 'revert that', 'undo what {agent} did', 'put it back the way it was', 'undo the last thing',
    'reverse that', 'undo the last change', 'go back to how it was', 'undo what you just did', "revert {agent}'s changes", 'can you undo that please',
    'undo that reminder', 'bring it back',
  ],
  activity_report: [
    'what did you do today', 'what have you done today', 'what did {agent} change', 'what have you been doing', 'tell me what you did',
    'what did you do yesterday', 'what did you do this week', 'give me a log of what you did', 'which apps did you open today',
    'what did {agent} do today', 'list what you did', 'what actions did you take',
  ],
  stop_everything: [
    'stop everything', 'stop it all', 'emergency stop', 'halt everything', 'kill everything now', 'shut it all down', 'stop all of it',
    'everything stop now', 'stop everything right now', 'abort everything', 'stop whatever you are doing, all of it', 'panic stop',
    'freeze everything', 'stop all of it immediately',
  ],
  permissions: [
    'what have i allowed', 'which things are you allowed to do without asking me', 'what permissions have i given you', 'what did i say always to',
    'which permissions have i given', 'which things do you not ask about', 'list my permissions', 'what have i let you do without asking',
    'what have i allowed {agent} to do without asking', 'read me my permissions', 'what did i allow you to do always',
  ],
  remind: [
    'remind me to call mum at 5', 'remind me at 6 to take my medicine', 'remind me tomorrow morning about the dentist', 'remind me tomorrow at 9 to send the report',
    'set a reminder for friday at 3 to pay the rent', 'remind me on monday to renew my passport', 'remind me tonight to charge my phone',
    'every weekday at 9 remind me to stand up', 'remind me every morning to drink water', 'remind me every friday to file my hours',
    'add buy milk to my reminders', 'put pick up the dry cleaning in my reminders', 'remind me at noon to eat lunch', 'remind me this evening to call kofi',
    'create a reminder for the 12th to pay my rent', 'remind me on the 1st of every month to pay the internet bill', 'can you remind me at half past four to leave for the airport',
    "don't let me forget to water the plants tomorrow", 'remind me next tuesday about the team lunch', 'remind me at 7 in the morning to go for a run',
    'remind me that the car needs a service on thursday', 'please remind me by 8 to prepare the slides', 'i need a reminder at 3 to join the call',
    'set me a reminder for tomorrow evening', 'make a reminder for sunday to call grandma', 'remember to call mum tomorrow', "don't forget to water the plants on friday",
    'add a reminder to my reminders list to book the flight', 'nova remind me on wednesday at 10 about the interview', 'remind me at 4pm to pick the kids up',
  ],
  reminders: [
    'what are my reminders', 'what reminders do i have', 'what reminders do i have today', 'do i have any reminders tomorrow', 'read me my reminders',
    'list my reminders', 'what have you got to remind me about', 'any reminders for today', 'what am i supposed to remember today', "what's coming up this week",
    'which reminders are set', 'tell me my reminders for tomorrow', 'have i got any reminders', 'what did i ask you to remind me about',
    'are there any reminders left today', 'read out my reminders please',
  ],
  cancel_reminder: [
    'cancel the reminder to call mum', 'delete my reminder about the dentist', 'remove the 5pm reminder',
    'get rid of the reminder about the rent', "i don't need the reminder about the meeting anymore", 'delete the friday reminder',
    'cancel the reminder for tomorrow morning', 'scrap the reminder to water the plants', 'remove my reminder to call kofi',
    'cancel the daily reminder to drink water', 'stop reminding me to stand up', 'delete the reminder about the team lunch',
  ],
  snooze_reminder: [
    'snooze', 'snooze it', 'snooze that', 'snooze for 10 minutes', 'snooze it for an hour', 'remind me again in 10 minutes', 'remind me again later',
    'ask me again in 5 minutes', 'snooze the reminder', 'give me ten more minutes then remind me', 'push it back half an hour', 'snooze that please',
    'snooze for five minutes nova', 'remind me about it again in an hour',
  ],
  reminder_done: [
    'mark it done', 'mark that as done', "i've done it", 'i did it', 'done with that', 'tick it off', 'complete that reminder', 'finished that one',
    'mark the reminder done', "that's done now", 'mark it as complete', "yes i've taken my medicine", 'already done it', 'mark it off my list',
  ],
  brief: [
    'brief me', 'good morning', 'morning nova', "what's my day like", "what's on today", 'give me my briefing', 'catch me up', 'what do i have on today',
    'run me through my day', 'how does my day look', 'daily briefing', 'morning briefing please', "what's happening today", 'what does today look like',
    "what's the plan for today", 'good morning, what have we got today', 'give me a rundown of today',
  ],
  missed: [
    'what did i miss', 'did i miss anything', 'anything while i was away', 'any news', 'what happened while i was gone', 'did anything come up',
    'any updates for me', 'what did i miss while i was in the meeting', 'catch me up on what i missed', "i'm back, anything new", 'did anyone need me',
    'what came up while i was out', 'anything i should know about since earlier',
  ],
  task_status: [
    'what are the agents doing', "how's {agent} getting on", 'is {agent} done yet', 'what did {agent} say', 'any update from the agents',
    "what's {agent} working on", 'is the agent finished', 'how is the task going', 'status of my tasks', 'did {agent} finish',
    'what is {agent} doing right now', 'check on the agents', 'are the agents still working', 'what did the agent find', 'how far is {agent} with it',
  ],
  set_project: [
    "i'm working on {project}", 'switch to the {project} project', 'my current project is {project}', "we're working on {project} today",
    "let's work on {project}", 'set my project to {project}', 'change project to {project}', "i'm on {project} now", 'focus on {project}',
    'the project today is {project}', 'work in {project} from now on', 'make {project} my current project',
  ],
  system_control: [
    'turn the volume up', 'turn the volume down', 'set the volume to 30', 'make it louder', 'make it a bit quieter', 'volume to fifty percent',
    'max volume', 'mute the volume', 'unmute the sound', "what's the volume at", 'turn it down a notch', 'turn the sound up a little',
    'dim the screen', 'make the screen brighter', 'brightness to 70', 'turn the brightness all the way up', 'lower the brightness',
    'turn on dark mode', 'switch to light mode', 'toggle dark mode', 'is dark mode on', 'turn off wifi', 'turn the wifi back on',
    'is my wifi on', 'disable bluetooth', 'turn bluetooth on', 'turn on do not disturb', 'turn off do not disturb', 'enable focus mode',
    'lock my screen', 'lock the mac', 'lock the computer please', 'put the mac to sleep', 'sleep the computer', 'how much battery do i have',
    'is my laptop charging', "what's my battery at", 'how long will the battery last', 'turn off the sound on the mac',
    'turn it up', 'a bit louder please', 'bit quieter please', 'lower the volume', 'raise the volume', 'increase the volume', 'decrease the volume',
    'turn the sound down a touch', 'can you make it louder', 'i can hardly hear it turn it up', "it's too loud turn it down", 'put the volume on 40',
    'volume at twenty five', 'set the sound to max', 'reduce the sound', 'mute my mac', 'mute the speakers', 'unmute my mac', 'sound off on the mac',
    'make the screen darker', 'screen brighter please', 'turn the brightness down', 'brightness up', 'brightness down a bit',
    'set the brightness to half', 'full brightness', 'dark mode please', 'switch to dark mode', 'go back to light mode', 'turn wifi off',
    'wifi on please', 'switch off the wifi', 'turn off the wireless', 'bluetooth off', 'switch bluetooth on', 'turn on bluetooth for my headphones',
    'do not disturb on', 'turn off my notifications', 'silence my notifications for a while', 'focus mode on please', 'end do not disturb',
    'lock the screen now', 'lock it up', 'lock my laptop', 'put the computer to sleep now', 'sleep the mac', "what's my battery level",
    'battery percentage', 'how much battery is left', 'am i charging', "how's the battery doing", 'what volume is it on', 'how bright is the screen',
    'is bluetooth on', 'is do not disturb on',
    'bring the volume down', 'bring the volume up', 'take the sound down', 'take the volume up a bit', 'drop the volume a little', 'boost the sound',
    'pump up the volume', 'crank the volume', 'lower the sound a bit', 'turn the speakers down', 'turn the speakers up', 'lower the volume by ten',
    'volume down a notch', 'put it on 30 percent', 'set it to half volume', 'turn the sound all the way down', 'mute the mac please',
    'silence the computer', "i can't hear it make it louder", 'turn the screen brightness up', 'dim the display a little', 'brighten it up',
    'full brightness please', 'brightness to 30', 'lower the brightness a lot', 'make the display brighter', 'dark mode on', 'dark mode off',
    'turn dark mode off', 'switch the theme to dark', 'change to light mode', 'night mode on', 'wifi off please', 'disconnect the wifi',
    'switch the wifi back on', 'bluetooth on please', 'turn bluetooth off', 'disable the bluetooth', 'is bluetooth switched on', 'turn wi-fi on',
    'turn on dnd', 'dnd off', 'no notifications for an hour', 'turn focus on', 'switch focus off', "i'm going into a meeting turn on do not disturb",
    'lock my computer', 'lock the laptop please', 'put the mac to sleep please', 'send the laptop to sleep', 'battery level', "how's my battery",
    'how much juice is left', 'is the laptop plugged in', "how long until it's charged", 'time left on the battery',
  ],
  text_size: [
    'make the text bigger', 'make the text smaller', 'bigger text please', 'smaller text please', 'increase the font size', 'decrease the font size',
    'the text is too small', 'the text is too big', "i can't read the text", 'the writing is too small to read', 'make the words bigger',
    'make the letters larger', 'can you make the font bigger', 'could you make the text a little smaller', 'text size up', 'text size down',
    'turn the text size up', 'turn the text size down', 'set the text size to 150 percent', 'text size 120 percent', 'make the text 130 percent',
    'put the font at 90 percent', 'reset the text size', 'text back to normal size', 'make the text normal again', 'default text size please',
    'double the text size', 'make the text twice as big', 'make the text one and a half times bigger', "what's the text size",
    'how big is the text right now', 'what size is the font', 'zoom in on the text', 'zoom out the text', 'enlarge the captions',
    'shrink the captions', 'bigger captions', 'make the transcript bigger', 'make the transcript text smaller', 'larger font',
    'make the font a lot bigger', 'make the text a bit bigger', 'bump up the text size', 'knock the text size down a bit',
    'the words are tiny, make them bigger', 'make your text easier to read', 'make the text more readable', 'shrink the font a little',
    'reduce the text size', 'grow the text', 'scale the text up', 'scale the text down', 'can you increase the text size please',
    'the subtitles are too small', 'make the subtitles bigger', 'make what you write bigger', 'make your words smaller',
    'bigger letters please', 'smaller font please', 'font size up a notch', 'put the text back to how it was', 'make the text huge',
    'make the text tiny', 'i need bigger text', 'larger text for me please', 'the font is way too big',
  ],
  media_control: [
    'pause the music', 'stop the music', 'resume the music', 'play the music again', 'next song', 'skip this song', 'skip this track',
    'previous track', 'go back a song', 'play the last song again', "what's playing", 'what song is this', "who's singing this", 'what is this track',
    'play some jazz', 'play my running playlist', 'play taylor swift', 'put on some music', 'play something relaxing', 'shuffle my liked songs',
    'pause spotify', 'resume spotify', 'next track on spotify', 'play some afrobeats', 'play the album abbey road', 'unpause the music',
    'keep playing', 'stop the podcast',
    'play music', 'start the music', 'music please', 'resume playing', 'carry on playing', 'pause it', 'pause the song', 'pause spotify for a sec',
    'hold the music', 'stop the song', 'skip song', 'next one please', 'play the next track', 'go to the next song', 'change the song',
    'another song please', 'go back one song', 'play the previous song', 'last track again', 'restart this song', 'what am i listening to',
    "what's this song called", 'who is this artist', 'name of this song', 'what album is this', 'play some music for cooking', 'play some drake',
    'play wizkid', 'play some old school hiplife', 'play my focus playlist', 'shuffle my music', 'play the beatles', 'put on some chill music',
    'play something i like', 'play music on spotify', 'play some worship songs', 'play some lofi beats', 'play my favourites', 'queue some jazz',
    'play some classical for studying',
    'pause the tune', 'stop this song', 'stop the track', 'play it again', 'keep the music going', 'start playing again', 'carry on with the music',
    'unpause it', 'skip to the next song', 'skip forward', 'next tune', 'skip the track', 'jump to the next song', 'play something else',
    'i want a different song', 'back one song', 'back to the last track', 'play that song again', 'start the song over', "what's this track",
    'what is playing right now', 'who sang this', "what's the name of this song", 'which artist is this', 'what song is playing', 'play some rnb',
    'play some reggae', 'play some kpop', 'play something to relax', 'play my road trip playlist', 'play the album thriller',
    'play songs by bob marley', 'play some sarkodie', 'play some stonebwoy', 'play some high life', 'play some party music',
    'play some music to sleep', 'shuffle my playlist', 'put some music on', 'play some tunes', 'turn the music on', 'turn the music off',
  ],
  window_control: [
    'put {app} on the left', 'move {app} to the right half', 'maximize {app}', 'maximize this window', 'move this window to the left side',
    'snap this to the right', 'put {app} on the right and {app} on the left', 'center this window', 'make {app} full screen', 'exit full screen',
    'minimize {app}', 'minimize this window', 'hide {app}', 'move {app} to the other screen', 'send this window to my other monitor',
    'put this in the top right corner', 'save this layout as work', 'save my windows as coding', 'set up my work layout', 'coding layout',
    'restore my writing layout', 'tile {app} and {app} side by side', 'split the screen between {app} and {app}', 'what windows are open',
    'make this window bigger', 'put {app} in the left third', 'arrange my windows for coding',
    'send {app} down to the dock', 'tuck this window into the dock', 'hide {app} for now', 'get {app} out of the way',
    'left half', 'put this on the left', 'this window to the right', 'snap left', 'snap right', 'tile this to the left', 'maximise',
    'make it full size', 'fill the screen', 'make this bigger', 'center it', 'put it in the middle', 'move {app} to the top right',
    'put {app} in the bottom left', '{app} top half', 'split the screen with {app} and {app}', '{app} left {app} right',
    'move {app} to my laptop screen', 'send {app} to the big monitor', 'put this on the other display', 'full screen please', 'exit full screen mode',
    'get out of full screen', 'minimise {app}', 'hide this app', 'show all my apps', 'unhide everything', 'what apps are open',
    'which windows are open', 'list my open windows', 'save my layout', 'remember this setup as focus', 'save these windows as meeting',
    'coding setup please', 'bring back my focus layout', 'restore the work layout', 'set up my windows for coding', 'arrange my windows for work',
    'put {app} on the left two thirds', 'make {app} take the right third', 'almost maximize this window', 'put {app} in the corner',
    'put this window on the left', 'put this window on the right', 'move it to the left', 'move it to the right', 'snap it left',
    'put {app} on the left half', 'put {app} on the right half', '{app} to the left', '{app} to the right', '{app} on the right', '{app} on the left',
    'move {app} over to the left', 'slide {app} to the right', 'make the window full size', 'make {app} bigger', 'maximise {app}',
    'make it fill the screen', 'center {app}', 'centre the window', 'put {app} in the middle', 'put it in the top right corner',
    'move {app} to the corner', 'send {app} to the other screen', 'move this to the other monitor', 'put {app} on my second screen',
    'move it to the laptop display', 'minimize the window', 'put {app} away', 'hide {app} please', 'full screen {app}', 'leave full screen',
    'show all windows', 'bring back all my apps', 'save my windows', 'save this arrangement as work', 'my coding layout', 'work layout please',
    'load my focus layout', 'set my windows up for work', 'put {app} and {app} side by side', '{app} and {app} side by side', 'split {app} and {app}',
  ],
  files: [
    'find my resume', 'where is the budget spreadsheet', 'find the pdf from my bank', 'where did i save the contract', 'show me my recent files',
    'what did i download today', 'show me my recent downloads', 'open the budget spreadsheet', 'open the invoice from yesterday',
    'open my notes file', 'reveal the report in finder', 'show the contract in finder', 'move the invoice to documents',
    'move this pdf to my desktop', 'rename report.pdf to final report', 'rename the screenshot to receipt', 'trash the screenshot on my desktop',
    'put the old invoice in the trash', 'delete the duplicate photo on my desktop', 'find all pdfs from last week', 'find the presentation about sales',
    'summarize the pdf in my downloads', "what's in the contract file", 'read the notes file to me', 'find photos from yesterday',
    'which files did i work on today', 'look for the tax documents',
    'bin that pdf', 'throw the spare copy in the trash', 'chuck that screenshot in the bin', 'put these downloads in the trash', 'where have i saved the scanned form',
    'find the invoice', 'look for my cv', 'search my files for the lease', 'find the photos from the wedding', 'find a pdf called budget',
    'where is my tax document', 'find the report i made last week', 'show me files from today', 'what did i download yesterday',
    'my recent documents', 'recent files please', 'latest downloads', 'open my cv', 'open the lease pdf', 'open the file called notes',
    'open that pdf i downloaded', 'open the latest invoice', 'show the budget in finder', 'reveal it in finder', 'where is that file saved',
    'move the pdf to my desktop', 'move it to documents', 'put the invoice in my work folder', 'move my screenshots to pictures',
    'rename it to final', 'rename the file to budget 2026', 'rename the pdf to signed contract', 'delete the file', 'trash that file',
    'put the screenshot in the trash', 'throw the installer away', 'delete the old copy', 'read the contract to me', 'what does the lease say',
    'summarise the report', "what's in the budget file", 'go through the minutes from the meeting', 'find my presentations',
    'find spreadsheets from this month', 'show me pdfs in downloads', 'find my screenshots from today', 'open the most recent download',
    'find the letter from the bank', 'look for the insurance documents', 'where are my photos from the trip',
    'find my cv', 'find my resume please', 'find the lease', 'find the contract', 'find my tax return', 'find the photos from last week',
    'find all my pdfs', 'find my spreadsheets', 'find my screenshots', 'find the file called budget', 'look for the invoice',
    'search for my passport photo', 'search my documents for the lease', 'where is the invoice', 'where is my cv', 'where did i save the report',
    "where's the contract", 'open the invoice', 'open the contract', 'open my resume', 'open the pdf', 'open the spreadsheet',
    'open the presentation', 'open the latest pdf', 'open the last file i downloaded', 'show me the report in finder', 'show it in finder',
    'recent downloads', 'my downloads from today', 'files from yesterday', 'what did i save today', 'show me what i downloaded',
    'move the file to documents', 'move this to downloads', 'put it in my documents', 'move the photos to pictures', 'rename this file',
    'rename the report', 'call the file final', 'delete that file', 'delete the screenshot', 'put it in the trash', 'move it to the trash',
    'read me the report', 'read the pdf', 'what does the contract say', "what's in the pdf", 'summarize the pdf', 'summarise the document',
    'sum up the report',
  ],
  clipboard: [
    "what's on my clipboard", 'what did i copy', 'read my clipboard', 'what have i copied', 'what is in the clipboard', 'copy that',
    'copy your answer', 'copy what you just said', 'copy that to the clipboard', 'copy the link', 'copy the page address', 'copy the url of this page',
    'put that on my clipboard', 'copy the last answer', 'copy it for me',
    "what's copied", 'read the clipboard', 'check my clipboard', 'clipboard please', "what's in my clipboard right now", 'what did i last copy',
    'show me what i copied', 'what text did i copy', 'copy the answer', 'copy what you said', 'copy that for me', 'put it on the clipboard',
    'save that to the clipboard', 'copy your reply', 'copy this answer to my clipboard', 'copy the link to this page',
    'copy the address of this site', 'copy this url', 'copy the page link', 'get me the url of this page', 'copy the link please',
    'put the link on my clipboard', 'copy the web address', 'can you copy that', 'copy the last thing you said', 'copy the summary',
    "what's on the pasteboard", 'read me my clipboard',
    'what is on the clipboard', "what's on the clipboard", 'read out my clipboard', 'what have i got on my clipboard', 'clipboard contents',
    'copy your answer please', 'copy the reply', 'copy that answer', 'save that to my clipboard', 'put your answer on the clipboard',
    'copy it to the clipboard', 'copy this page link', 'copy the website link', 'copy the url please', 'copy the address of this page',
    'get the link to this page', 'copy the link of this site',
  ],
  run_shortcut: [
    'run my log water shortcut', 'run the morning shortcut', 'run shortcut translate', 'run my shortcut called focus', 'start the commute shortcut',
    'trigger my home shortcut', 'run the shortcut to log my weight', 'what shortcuts do i have', 'list my shortcuts', 'run translate with good morning',
    'run my timesheet shortcut', 'do my evening shortcut', 'run the shortcut for the lights', 'can you run my playlist shortcut',
    'run my morning routine shortcut', 'run the lights shortcut', 'run my commute shortcut', 'start my focus shortcut', 'do the log water shortcut',
    'run a shortcut', 'run shortcut morning', 'use my translate shortcut', 'run the shortcut called send eta', 'trigger my evening shortcut',
    'launch my workout shortcut', 'run my expenses shortcut', 'play my podcast shortcut', 'run the timesheet shortcut',
    'kick off my standup shortcut', 'can you run the dim lights shortcut', 'run my bedtime shortcut', 'run my reading shortcut',
    'run translate on bonjour', 'run my summarize shortcut with this', 'which shortcuts can you run', 'show me my shortcuts',
    'what shortcuts are there', 'list all my shortcuts', 'how many shortcuts do i have', 'run the battery level shortcut',
    'run the log mood shortcut', 'start the meditation shortcut', 'do my morning shortcut please', 'run my lumos shortcut',
    'run my shortcut called morning', 'run the morning shortcut please', 'run the evening routine shortcut', 'run the commute shortcut',
    'can you run a shortcut', 'run my timer shortcut', 'run my notes shortcut', 'run the shortcut named home', 'use the shortcut called translate',
    'run my lights on shortcut', 'run my lights off shortcut', 'launch the focus shortcut', 'trigger the morning shortcut',
    'run the play pause shortcut', 'run take screenshot shortcut', 'run my haiku shortcut', 'list shortcuts', 'show shortcuts',
    'which of my shortcuts can you run',
  ],
  ui_control: [
    'click send', 'click the reply button', 'click on submit', 'press the ok button', 'double click the report', 'right click the icon',
    'type hello world', 'type my message', 'type dear john and press enter', 'press enter', 'hit return', 'press command s', 'press escape',
    'press the down arrow twice', 'scroll down', 'scroll up a bit', 'scroll to the top', 'go to the bottom of the page', 'select all',
    'press command z', 'hit tab', 'click accept', 'click next', 'click the save button',
    'type see you soon', 'type in on my way home', 'type thanks see you later', 'type in running ten minutes late',
    'click ok', 'click cancel', 'click done', 'click the blue button', 'click on the link', 'click continue', 'press the send button', 'tap next',
    'hit reply', 'click save', 'click accept all', 'click sign in', 'click on the first result', 'click the search bar', 'double click it',
    'right click on it', 'type my name', 'type the word hello', 'write hello in the box', 'type yes', 'press tab', 'press space', 'press delete',
    'hit escape', 'press enter twice', 'press command c', 'press command v', 'press the up arrow', 'press down', 'hit backspace',
    'press command shift t', 'scroll down a bit', 'scroll to the bottom', 'scroll down the page', 'page down', 'go to the top of the page',
    'scroll right', 'select everything', 'select all the text', 'highlight all',
    'click the button', 'click the ok button', 'click the cancel button', 'click on send', 'click on reply', 'click on save', 'click submit',
    'click the send button', 'tap the button', 'hit send', 'hit enter', 'press return', 'hit the return key', 'press the tab key',
    'press the space bar', 'press backspace', 'press command a', 'press command s please', 'press control c', 'press command tab', 'type hello',
    'type okay', 'type thank you', 'type on my way', 'type my email', 'type this for me', 'scroll down please', 'scroll up please',
    'scroll down a lot', 'scroll all the way down', 'go to the bottom', 'double click on the folder', 'right click on the file', 'select all please',
  ],
  computer_task: [
    'use the computer to book a table', 'take over and fill in this form', 'use my mac to order more coffee pods', 'do it for me on the computer',
    'use the computer to find a flight to london', 'go to amazon and add batteries to my cart', 'take over the mouse and do it', 'fill out this form for me',
    'use the browser to check my bank balance', 'do this on screen for me', 'use the computer to reply to that email', 'take control and sort this out',
    'use safari to look up the train times and book one', 'can you use the computer for me', 'operate the computer and set this up',
    'use the computer and book me a taxi', 'can you do this on my mac', 'take over my screen and finish this', 'go through this form for me',
    'do the online check in for me', 'buy this on the website for me', 'order it for me on the site', 'use the browser to pay my bill',
    'go to my bank and download the statement', 'complete the signup form', 'fill in the details on this page',
    'book a flight to kumasi on the website', 'use the computer to send an email to my boss', 'reply to this email for me using the screen',
    'you do it on the computer', 'handle it on the screen', 'use safari to find me a hotel and book it', 'go online and renew my licence',
    'pay the dstv bill on the website', 'add these items to my cart and check out', 'navigate the site and cancel my subscription',
    'click through the setup for me', 'set this up for me on the screen', 'install the update for me', 'can you finish filling this form',
    'use chrome to look up the train times and book a seat', 'do the whole thing for me on the computer', 'use the mouse and keyboard to do it',
    'control my computer and sort out the spreadsheet', 'take control and upload my documents to the portal', 'fill my timesheet in on the website',
    'submit the form for me', 'enter my address on the checkout page', 'order a pizza online for me',
    'use the computer to do it', 'do it on the computer for me', 'take over the computer', 'take over and do it', 'use my computer to do this',
    'fill in the form for me', 'complete this form for me', 'book it for me on the website', 'order it online for me', 'buy it for me online',
    'go through the website and book it', 'do the booking for me', 'sign me up on the website', 'check me in online', 'pay my bill online',
    'use the browser to do it', 'go on the website and do it', 'can you use the computer for this', 'take over the screen',
    'drive the computer for me', 'go ahead and use the computer', 'do this task on the screen',
  ],
  create_routine: [
    'when i say start work open slack and brief me', 'when i say good night mute yourself', 'every weekday at 9 open linear and brief me',
    'make a routine that opens my email when i say good morning', 'whenever i say focus time quit slack', 'set up a routine for the morning',
    'when i say lunch time remind me to stretch', 'every friday at 5 open my timesheet', 'add a routine when i say standup open zoom',
    "when i say let's code open visual studio code", 'create a routine for when i get to work', 'when i say wrap up quit slack and tell me my reminders',
    'every morning at 8 brief me and open my calendar',
  ],
};
